// Conteúdo do jogo. Depois de editar, rode: node tools/build.js
window.OUTERDLE_DATA = (() => {
  "use strict";

  // LOCAIS
  //   corpo    corpo celeste onde fica (planetas/luas apontam pra si mesmos)
  //   orbita   posição a partir do Sol; null = varia (Lua Quântica)
  //   nomai    "Sim" (estrutura ativa), "Ruínas" ou "Não"
  //   viajante quem acampa ali
  //   dicas    5 frases nossas, da mais vaga à mais específica; o modo Locais usa a 2ª e a 4ª
  //   diario   registros reais do diário de bordo (tradução oficial pt-BR), 3 a 6.
  //            Sem esse campo o lugar fica fora do modo Diário.
  //   dlc      só aparece com Echoes of the Eye ligado
  const LOCAIS = [
    // Sol
    { id:"sol", nome:"Sol", alias:["Sun","The Sun","O Sol"],
      tipo:"Estrela", corpo:"Sol", orbita:0, nomai:"Não", perigo:"Calor", viajante:"Nenhum",
      desc:"A estrela do sistema. Está velha, inchada e prestes a fazer algo dramático.",
      dicas:["Sem mim, nada por aqui estaria girando.","Ando maior e mais vermelho do que deveria.","Construíram uma estação bem perto de mim, e não era pra me admirar de longe.","Cherte já percebeu que tem algo errado comigo.","No fim de cada ciclo, eu explodo."] },
    { id:"sun-station", nome:"Estação Solar", alias:["Sun Station"],
      tipo:"Estação", corpo:"Sol", orbita:1, nomai:"Sim", perigo:"Calor", viajante:"Nenhum",
      desc:"Estação Nomai em órbita rasante do Sol, construída pra um experimento que nunca funcionou.",
      dicas:["Nada aqui saiu como o planejado.","Fico onde nenhuma nave deveria conseguir chegar.","Você só chega em mim por um caminho que não é a sua nave.","Fui construída pra forçar o Sol a fazer algo que ele ainda não estava pronto pra fazer.","Pye escreveu nas minhas paredes que eu era um fracasso."],
      diario:["Há um modo seguro de viajar do Gêmeo Cinzento até a Estação Solar.","Os Nomai discutiram sobre construir uma Estação Solar a fim de energizar o Projeto do Gêmeo Cinzento.","Os Nomai construíram algo chamado de Estação Solar, mas nem todos aprovaram sua construção.","A Estação Solar foi desenvolvida para forçar o sol a ser uma supernova.","Os Nomai dispararam a Estação Solar, mas não afetou o sol. Eles concluíram que a Estação Solar nunca conseguiria levar o sol a ser uma supernova.","Após a Estação Solar falhar, os Nomai deram uma pausa para investigar o cometa recém-chegado."] },

    // Gêmeo Cálido
    { id:"ember-twin", nome:"Gêmeo Cálido", alias:["Gêmea de Brasa","Gêmea de Brasas","Ember","Ember Twin"],
      tipo:"Planeta", corpo:"Gêmeo Cálido", orbita:2, nomai:"Sim", perigo:"Areia", viajante:"Cherte",
      desc:"A gêmea que recebe areia. Cavernas, uma cidade escondida e Cherte no topo.",
      dicas:["Meu vizinho está me enchendo. Literalmente.","Tem uma cidade escondida onde o sol não bate.","Minhas cavernas ficam mais apertadas conforme o ciclo avança.","Um astrônomo acampa no meu topo tocando tambor.","A Cidade Sem Sol e o Laboratório de Alta Energia ficam em mim."] },
    { id:"chert-camp", nome:"Acampamento de Chertee", alias:["Acampamento de Chertee","Cherte's Camp","Acampamento do Cherte"],
      tipo:"Acampamento", corpo:"Gêmeo Cálido", orbita:2, nomai:"Não", perigo:"Nenhum", viajante:"Cherte",
      desc:"Uma cratera no polo norte do Gêmeo Cálido, com um telescópio, um tambor e um astrônomo cada vez mais nervoso.",
      dicas:["Fico numa cratera no topo de um planeta que só piora com o tempo.","Tenho um telescópio apontado pro céu e um tambor.","A coluna de areia do vizinho passa bem do meu lado.","Quem acampa aqui vai ficando menos animado conforme o ciclo passa.","Cherte está aqui."],
      diario:["Todas as estrelas do universo estão morrendo, inclusive nosso sol.","As estrelas simplesmente estão morrendo de velhice. Aparentemente elas são mais velhas do que imaginávamos.","Cherte montou seu equipamento de astronomia no polo norte do Gêmeo Cálido.","Cherte observou um estranho aumento no número de supernovas recentemente.","Cherte entrou em estado catatônico ao saber da morte iminente do nosso sol."] },
    { id:"sunless-city", nome:"Cidade do Ocaso", alias:["Sunless City","Cidade sem sol","Cidade Sem Sol"],
      tipo:"Cidade", corpo:"Gêmeo Cálido", orbita:2, nomai:"Sim", perigo:"Areia", viajante:"Nenhum",
      desc:"A cidade Nomai escavada num cânion do Gêmeo Cálido, longe do calor do Sol. A areia acaba tomando tudo.",
      dicas:["Fui construída onde o sol nunca chega.","Casas de pedra em camadas, dentro de um cânion.","A areia vai me enchendo ao longo do ciclo.","Tenho um santuário dedicado a estudar a lua que some.","Fico embaixo da superfície do Gêmeo Cálido."],
      diario:["Os sobreviventes que caíram no Gêmeo Cálido decidiram buscar abrigo nas cavernas, sob o local da queda da cápsula de escape deles.","Os Nomai descobriram um lugar para abrigarem-se em longo prazo, no fim de umas das passagens sob a cápsula de escape.","Cherte crê que a falta de ruínas na superfície mostra que os Nomai devem ter vivido no subterrâneo.","Há um caminho que leva até o Laboratório de Alta Energia da Cidade do Ocaso.","Eu encontrei um indicador de trilha para a Cidade do Ocaso, mas o caminho está bloqueado.","Uma cidade Nomai construída nas paredes de uma enorme caverna subterrânea. A cidade é dividida verticalmente em quatro distritos."] },
    { id:"high-energy-lab", nome:"Laboratório de Alta Energia", alias:["High Energy Lab","Lab de Alta Energia"],
      tipo:"Laboratório", corpo:"Gêmeo Cálido", orbita:2, nomai:"Sim", perigo:"Nenhum", viajante:"Nenhum",
      desc:"Onde os Nomai provaram que algo pode chegar antes de sair. Pye trabalhou aqui.",
      dicas:["Foi aqui que se provou que uma coisa pode chegar antes de partir.","Um buraco negro e um buraco branco pequenos, feitos de propósito.","Pye trabalhou aqui.","Fico num cânion perto do equador de um planeta de areia.","Fico no Gêmeo Cálido, e a cidade fica logo ao lado."],
      diario:["Os Nomai conseguiram reproduzir com sucesso a anomalia temporal observada a princípio na Estação do Buraco Branco (objetos transportados parecem chegar antes de partir).","O intervalo de tempo negativo medido na Estação do Buraco Branco foi investigado profundamente no Laboratório de Alta Energia (no canyon no equador Gêmeo Cálido).","O Projeto do Gêmeo Cinzento foi concebido no Laboratório de Alta Energia, um prédio com grandes painéis solares no equador no Gêmeo Cálido.","O Laboratório de Alta Energia só pode ser acessado pela trilha da Cidade do Ocaso.","Os Nomai descobriram que conseguiriam aumentar o intervalo de tempo negativo entre chegada e partida, adicionando energia nos núcleos de transportação.","Os Nomai queriam saber se um intervalo negativo de 22 minutos seria possível. Eles concluíram que era preciso uma nova tecnologia para produzir a energia necessária, assim como um núcleo de translação avançado capaz de suportá-la. O Gêmeo Cinzento foi sugerido como o local para esse projeto."] },
    { id:"lakebed-cave", nome:"Caverna do Fundo Seco do Lago", alias:["Caverna do Fundo do Lago","Lakebed Cave","Cavernas Quânticas","Caverna do Leito do Lago","Caverna do Lago Seco"],
      tipo:"Caverna", corpo:"Gêmeo Cálido", orbita:2, nomai:"Ruínas", perigo:"Areia", viajante:"Nenhum",
      desc:"Um lago que secou há eras. Lá dentro, uma pedra que muda de lugar quando ninguém olha.",
      dicas:["Um lago que secou há muito tempo.","Lá dentro tem uma pedra que muda de lugar quando ninguém olha.","Coleus sumiu aqui.","Aqui se aprende a primeira regra quântica.","Fico no Gêmeo Cálido e encho de areia rápido."],
      diario:["Um Nomai chamado Coleus estava em cima da pedra errante quando outra lanterna Nomai se apagou. Quando religaram a lanterna, Coleus e a pedra haviam sumido.","Coleus e Melorae voltaram para analisar a rocha. Na teoria deles, quando um ser consciente entra em contato com um objeto quântico e deixa de observar os arredores, eles podem ficar presos e se moverem juntos.","A rocha errante foi vista pela primeira vez na caverna no fundo seco do lago no polo norte do Gêmeo Cálido.","Um Nomai chamado Coleus desapareceu misteriosamente da caverna no fundo seco do lago no polo norte do Gêmeo Cálido.","Para viajar com um objeto quântico, é necessário ficar sobre o objeto e deixar de observar seus arredores (significando que tem que haver uma completa escuridão). Coleus usou essa regra quântica para escapar da caverna onde ficou preso."] },
    { id:"escape-pod-2", nome:"Cápsula de Escape 2", alias:["Pod de Fuga 2","Escape Pod 2","Pod 2","Cápsula de Fuga 2"],
      tipo:"Ruína", corpo:"Gêmeo Cálido", orbita:2, nomai:"Ruínas", perigo:"Areia", viajante:"Nenhum",
      desc:"O pod que teve o pouso mais violento. Quem estava dentro sobreviveu por pouco.",
      dicas:["Caí com força e fiquei de lado.","Quem estava dentro sobreviveu, mas por pouco.","Filix saiu daqui pra explorar.","Sou um de três, e o que mais sofreu na chegada.","Fico no Gêmeo Cálido, meio enterrado."],
      diario:["Cherte encontrou destroços Nomai emitindo um sinalizador de luz para o céu, em algum lugar no hemisfério sul do Gêmeo Cálido.","Uma das três cápsulas de escape Nomai pousou em algum lugar nos Gêmeos da Ampulheta.","Uma das três cápsulas de escape Nomai que caíram em nosso sistema solar.","Todas as três cápsulas de escape foram lançadas de algo chamado O Hospedeiro, que estava bem danificado."] },
    { id:"quantum-moon-locator", nome:"Radar da Lua Quântica", alias:["Localizador da Lua Quântica","Quantum Moon Locator","Localizador Quântico"],
      tipo:"Estrutura", corpo:"Gêmeo Cálido", orbita:2, nomai:"Sim", perigo:"Nenhum", viajante:"Nenhum",
      desc:"Um mapa Nomai que mostra em qual planeta a Lua Quântica está agora.",
      dicas:["Fico de olho em algo que muda de lugar.","Sou um mapa do sistema com uma marca que anda sozinha.","Mostro em qual planeta a lua está agora.","Fui feito pelos Nomai pra planejar peregrinações.","Fico na superfície do Gêmeo Cálido, perto do polo norte."],
      diario:["Um dispositivo Nomai criado para rastrear a localização da Lua Quântica.","Segundo os Nomai, a Lua Quântica deve ser alguma forma de mecânica quântica macroscópica.","A Lua Quântica vaga por cinco locais ao todo."] },

    // Gêmeo Cinzento
    { id:"ash-twin", nome:"Gêmeo Cinzento", alias:["Gêmea de Cinzas","Ash","Ash Twin"],
      tipo:"Planeta", corpo:"Gêmeo Cinzento", orbita:2, nomai:"Sim", perigo:"Areia", viajante:"Nenhum",
      desc:"A gêmea que perde areia. Torres de dobra e um projeto secreto no núcleo.",
      dicas:["Vou embora aos poucos, grão por grão.","Minhas torres levam pra cada um dos outros mundos.","Uma coluna de areia me liga ao meu gêmeo.","O que guardo no meu núcleo é a razão de você lembrar de tudo.","O projeto que leva meu nome fica bem no meu centro."] },
    { id:"ash-twin-project", nome:"Projeto do Gêmeo Cinzento", alias:["Ash Twin Project","Projeto Gêmea de Cinzas","ATP","Projeto Ash Twin"],
      tipo:"Laboratório", corpo:"Gêmeo Cinzento", orbita:2, nomai:"Sim", perigo:"Nenhum", viajante:"Nenhum",
      desc:"O maior segredo dos Nomai, escondido no centro do Gêmeo Cinzento. É por causa dele que você lembra de tudo.",
      dicas:["Fico no centro de um planeta que está esvaziando.","Recebo energia de algo muito maior que eu.","Guardo a memória de tudo que você já viveu.","Só se entra em mim quando a areia libera o caminho.","Fui o maior segredo dos Nomai."],
      diario:["Há oito monólitos com máscaras Nomai presas. Três dessas máscaras estão recebendo dados respectivamente do Módulo de Rastreamento de Sonda, do Profundezas do Gigante e do Recanto Lenhoso.","A câmara central dentro do Gêmeo Cinzento foi selada fisicamente por um imenso e robusto invólucro protetor.","Os Nomai planejaram construir uma tecnologia capaz de produzir um intervalo de tempo negativo de 22 minutos no Gêmeo Cinzento.","Cada memória gravada por uma estátua Nomai é transmitida à unidade de armazenamento correspondente dentro do Gêmeo Cinzento.","Um núcleo de translação avançado foi aprovado para ser instalado na câmara central do Gêmeo Cinzento.","Uma câmara vazia dentro do Gêmeo Cinzento. Os cabos de energia da superfície foram conectados a um invólucro protetor no centro do planeta."] },
    { id:"ash-twin-towers", nome:"Torres do Gêmeo Cinzento", alias:["Ash Twin Towers","Torres de Teletransporte","Torres de Dobra"],
      tipo:"Torre", corpo:"Gêmeo Cinzento", orbita:2, nomai:"Sim", perigo:"Areia", viajante:"Nenhum",
      desc:"Torres alinhadas no equador do Gêmeo Cinzento. Cada uma tem a forma do mundo pra onde leva.",
      dicas:["Cada uma de nós tem a forma do lugar pra onde leva.","Pisar em cima na hora certa te leva pra outro mundo.","Ficamos alinhadas no equador de um planeta.","A areia nos cobre e descobre ao longo do ciclo.","Ficamos no Gêmeo Cinzento."] },

    // Recanto Lenhoso
    { id:"timber-hearth", nome:"Recanto Lenhoso", alias:["Timber","Timber Hearth"],
      tipo:"Planeta", corpo:"Recanto Lenhoso", orbita:3, nomai:"Ruínas", perigo:"Matéria fantasma", viajante:"Nenhum",
      desc:"Casa. Gêiseres, pinheiros, uma vila na cratera e uma plataforma de lançamento.",
      dicas:["Pra você, tudo começa aqui.","Gêiseres, pinheiros e uma cratera com uma vila.","Meu museu acabou de receber uma estátua que não para de olhar pra você.","Ardósia, Corneana e Gossan moram aqui.","Sua nave decola da minha vila."] },
    { id:"vila", nome:"Vila", alias:["Village","Vila Lenhosa","Aldeia"],
      tipo:"Cidade", corpo:"Recanto Lenhoso", orbita:3, nomai:"Não", perigo:"Nenhum", viajante:"Nenhum",
      desc:"Casas de madeira numa cratera, uma árvore enorme no meio e todo mundo que você conhece.",
      dicas:["Casas de madeira dentro de uma cratera.","Tenho uma árvore enorme no meio, que Marga quer derrubar.","Crianças brincam de esconde-esconde por aqui.","É daqui que sua nave decola.","É onde os Lenhosos moram."],
      diario:["A estátua Nomai no observatório abriu os olhos e me olhou! Vi estranhas luzes brilhantes e as minhas próprias memórias passaram diante de meus olhos.","Hal disse que a estátua nunca abriu os olhos antes (apesar de Corneana ter tentado).","A primeira e única vila Lenhosa, assim como a principal origem das explosões esse planeta."] },
    { id:"museu", nome:"Museu", alias:["Museum","Observatório do Recanto Lenhoso","Observatório"],
      tipo:"Observatório", corpo:"Recanto Lenhoso", orbita:3, nomai:"Não", perigo:"Matéria fantasma", viajante:"Nenhum",
      desc:"O observatório da vila, com uma exposição de tudo que a Outer Wilds Ventures já achou. Hal cuida dele.",
      dicas:["Guardo uma pedra que dá pra segurar mas não dá pra entender.","Tenho uma amostra de algo invisível que mata, dentro de uma caixa.","Hal cuida de mim.","Uma estátua recém-chegada abre os olhos pra você aqui.","Fico no alto da vila."] },
    { id:"zero-g-cave", nome:"Caverna de Gravidade Zero", alias:["Zero-G Cave","Caverna Gravidade Zero","Caverna de gravidade"],
      tipo:"Caverna", corpo:"Recanto Lenhoso", orbita:3, nomai:"Não", perigo:"Nenhum", viajante:"Nenhum",
      desc:"Onde os novatos aprendem a flutuar e a consertar coisas antes de sair pro espaço.",
      dicas:["Aqui você flutua.","Sirvo pra treinar antes de sair pro espaço.","Você conserta uma nave de mentira aqui antes de pilotar a de verdade.","Gossan te espera na entrada.","Fico embaixo da vila."],
      diario:["Eu consertei brilhantemente outro “satélite” para Gossan.","Soube que Gossan preparou a caverna de gravidade zero caso eu precisasse me atualizar antes do lançamento.","Uma caverna no centro do Recanto Lenhoso e utilizada pelo Outer Wilds Ventures para treinar novos astronautas."] },
    { id:"minas-nomai", nome:"Minas Nomai", alias:["Nomai Mines","Mina","Minas"],
      tipo:"Caverna", corpo:"Recanto Lenhoso", orbita:3, nomai:"Ruínas", perigo:"Matéria fantasma", viajante:"Nenhum",
      desc:"Escavações Nomai que os Lenhosos reaproveitaram e depois fecharam. Tem algo invisível lá dentro.",
      dicas:["Ninguém da vila deveria entrar aqui.","Os Lenhosos me usaram e depois me fecharam.","Tem algo invisível lá dentro que mata.","Os Nomai começaram a escavar aqui muito antes.","Fico na cratera do Recanto Lenhoso, longe da vila."],
      diario:["Os Nomai estavam extraindo minérios em algum lugar no Recanto Lenhoso.","Os Nomai extraíram minérios desse lugar para construir um invólucro protetor, desenvolvido para selar fisicamente a câmara central dentro do Gêmeo Cinzento.","Assim que o invólucro foi finalizado, os Nomai verificaram para garantir que não havia mais nenhuma entrada física ou rachadura.","Os Nomai descobriram uma espécie de forma de vida semiaquática de quatro olhos nos canais próximos à mina."] },
    { id:"radio-tower", nome:"Torre de Rádio", alias:["Radio Tower"],
      tipo:"Torre", corpo:"Recanto Lenhoso", orbita:3, nomai:"Não", perigo:"Nenhum", viajante:"Nenhum",
      desc:"Uma das poucas construções Lenhosas fora da cratera, do outro lado do planeta.",
      dicas:["Fico bem longe da vila, do outro lado do planeta.","Fui construída pra ouvir sinais de longe.","Sou uma das poucas construções Lenhosas fora da cratera.","Dá pra ver a lua bem de perto daqui.","Fico no Recanto Lenhoso."] },
    { id:"launch-pad", nome:"Plataforma de Lançamento", alias:["Launch Pad","Plataforma"],
      tipo:"Estrutura", corpo:"Recanto Lenhoso", orbita:3, nomai:"Não", perigo:"Nenhum", viajante:"Nenhum",
      desc:"Uma torre de madeira com um elevador. Sua nave está lá em cima, e Ardósia lá embaixo.",
      dicas:["Foi de onde tudo começou, pra você.","Um elevador de madeira leva até o meu topo.","Ardósia fica na minha base, sempre mexendo em algo.","Sua nave está estacionada em mim, se você ainda não decolou.","Fico na vila."] },

    // Pedra de Lia
    { id:"attlerock", nome:"Pedra de Lia", alias:["Lua do Recanto Lenhoso","Attlerock","Pedra de Lia"],
      tipo:"Lua", corpo:"Pedra de Lia", orbita:3, nomai:"Ruínas", perigo:"Nenhum", viajante:"Esker",
      desc:"A lua do Recanto Lenhoso. Pequena, cinzenta e com um único morador.",
      dicas:["Pequena, cinzenta e cheia de crateras.","Tenho um posto de observação apontado pra um sinal distante.","Meu único morador assobia pra passar o tempo.","Fico girando em volta da sua casa.","Esker mora aqui e reclama que ninguém visita."] },
    { id:"esker-camp", nome:"Acampamento de Esker", alias:["Esker's Camp","Posto Lunar","Lunar Lookout"],
      tipo:"Acampamento", corpo:"Pedra de Lia", orbita:3, nomai:"Não", perigo:"Nenhum", viajante:"Esker",
      desc:"O posto de observação lunar. Tem um telescópio de sinais e alguém assobiando.",
      dicas:["Sou o acampamento mais perto de casa.","Tenho um telescópio de sinais pra ouvir todo mundo.","Alguém fica aqui assobiando, esperando visita.","Fico numa lua cinzenta.","Esker mora aqui."],
      diario:["Parece que Esker ainda está na Pedra de Lia. Já está lá há algum tempo.","Esker está cultivando mudas de árvores em seu acampamento. Aparentemente está se dando bem lá, mas pode estar só a tempo demais.","Esker diz que o polo norte da Pedra de Lia (marcado em vermelho no minimapa) é um ótimo lugar para escutar a música dos demais viajantes com um onduloscópio.","Uma plataforma de observação com uma vista espetacular do sistema solar. Esker usa seu onduloscópio aqui para ficar de olho nos outros viajantes."] },

    // Vale Incerto
    { id:"brittle-hollow", nome:"Vale Incerto", alias:["Brittle","Brittle Hollow"],
      tipo:"Planeta", corpo:"Vale Incerto", orbita:4, nomai:"Sim", perigo:"Buraco negro", viajante:"Riebeck",
      desc:"Um planeta desmoronando num buraco negro, com uma cidade pendurada sob a crosta.",
      dicas:["Tenho um buraco no meio. Literalmente.","Pedaços do meu chão somem de vez em quando.","Uma cidade foi construída pendurada sob a minha crosta.","Riebeck acampa perto das minhas ruínas, morrendo de medo de voar de volta.","A Cidade Suspensa e a Forja do Buraco Negro ficam em mim."] },
    { id:"hanging-city", nome:"Cidade Dependurada", alias:["Hanging City","Cidade Pendurada","Cidade Suspensa"],
      tipo:"Cidade", corpo:"Vale Incerto", orbita:4, nomai:"Sim", perigo:"Buraco negro", viajante:"Nenhum",
      desc:"A cidade Nomai pendurada de cabeça pra baixo sob a crosta do Vale Incerto, dividida em distritos.",
      dicas:["Fui construída pendurada, de cabeça pra baixo.","Tenho um elevador que sobe pelos meus distritos.","Fico embaixo da crosta de um planeta que está desabando.","Daz cresceu aqui.","A Forja pode ser içada até mim."],
      diario:["Os Nomai decidiram migrar para o Antigo Assentamento na geleira norte. Eles usaram cristais de gravidade para criar um caminho estável por baixo da superfície.","Eu encontrei uma alavanca no Distrito do Degelo que eleva e rebaixa a Usina de Buracos Negros.","Os Nomai discutiram sobre como obter o poderoso e altamente avançado núcleo de transportação necessário para o Projeto do Gêmeo Cinzento.","Os Nomai viajaram para esse sistema solar atrás de um sinal mais antigo que o próprio universo. Eles chamaram a fonte desse sinal de o “Olho do universo”.","Há uma grande cidade Nomai ao norte do acampamento de Riebeck.","Uma cidade Nomai suspensa sob a geleira norte do Vale Incerto. A cidade é dividida verticalmente em quatro distritos."] },
    { id:"black-hole-forge", nome:"Usina de Buracos Negros", alias:["Black Hole Forge","Forja","Forja do Buraco Negro"],
      tipo:"Estrutura", corpo:"Vale Incerto", orbita:4, nomai:"Sim", perigo:"Buraco negro", viajante:"Nenhum",
      desc:"Onde os Nomai forjavam núcleos de dobra, pendurada bem em cima do buraco negro.",
      dicas:["Foi aqui que os núcleos de dobra eram feitos.","Fico pendurada perto do centro de um planeta.","Preciso ser içada pra você entrar.","Você me aciona na Cidade Suspensa.","Fico sob o Vale Incerto, logo acima do buraco negro."],
      diario:["O ponto de alinhamento de uma torre de translação não é seu receptor de translação. Na verdade, uma torre de translação sempre se alinha com o centro do seu corpo astral correspondente.","O receptor de translação precisa estar localizado no corpo astral relevante (ou em órbita próxima).","A Usina de Buracos Negros é suspensa e fica acima da Cidade Dependurada. Eu encontrei uma alavanca no Distrito do Degelo que eleva e rebaixa a Usina.","O Distrito da Usina de Buracos Negros é o distrito mais alto na Cidade Dependurada.","Uma Nomai chamada Poke tentou criar um núcleo avançado de transportação na Usina de Buracos Negros.","Os Nomai construíram núcleos de translação na Usina de Buracos Negros antes de enviá-los para o Gêmeo Cinzento."] },
    { id:"tower-quantum-knowledge", nome:"Torre do Conhecimento Quântico", alias:["Tower of Quantum Knowledge","Torre Quântica"],
      tipo:"Torre", corpo:"Vale Incerto", orbita:4, nomai:"Sim", perigo:"Buraco negro", viajante:"Nenhum",
      desc:"A torre no polo sul do Vale Incerto que guarda a terceira regra quântica. Uma hora ela cai.",
      dicas:["Ensino a terceira regra.","Fico no polo sul de um planeta frágil.","Uma hora eu caio.","Depois de cair, dá pra entrar em mim por outro lado.","Explico como visitar o lugar que a lua não mostra."],
      diario:["Os Nomai construíram um templo na Lua Quântica para ajudá-los na peregrinação até a sexta localização. \"Não se esqueça da regra final: Para explorar a sexta localização, o templo precisa estar no polo norte da lua\".","A peregrinação à Lua Quântica era uma viagem significativa para um Nomai.","Após os dois grupos de Nomai isolados no Gêmeo Cálido e no Vale Incerto se reunirem, encontrar e visitar a Lua Quântica tornou-se o objetivo comum a eles.","Essa torre (localizada no equador do Vale Incerto) guarda conhecimento útil para os Nomai que embarcaram em suas peregrinações à Lua Quântica.","Disseram para uma Nomai chamada Solanum visitou a Torre do Conhecimento Quântico (no equador do Vale Incerto) para aprender sobre a regra final, antes de embarcar em sua peregrinação à Lua Quântica."] },
    { id:"southern-observatory", nome:"Observatório do Sul", alias:["Southern Observatory","Observatório Sul"],
      tipo:"Observatório", corpo:"Vale Incerto", orbita:4, nomai:"Sim", perigo:"Buraco negro", viajante:"Nenhum",
      desc:"De onde os Nomai olharam pra um sinal que não conseguiam ver. Tem um modelo do sistema inteiro.",
      dicas:["Fico na ponta de baixo de um planeta.","Foi daqui que os Nomai olharam pra um sinal que não conseguiam enxergar.","Tenho um modelo do sistema que mostra o que a sonda deveria achar.","Fico perto de um cruzamento de caminhos Nomai.","Fico no polo sul do Vale Incerto."],
      diario:["Os Nomai decidiram criar um radar maior e mais elaborado para captar o sinal do Olho no polo sul do Vale Incerto.","De acordo com o conhecimento deles sobre a Lua Quântica, os Nomai acreditavam que o Olho estava em uma órbita distante do sol.","Há duas trilhas abaixo da superfície do Vale Incerto que levam ao observatório. Uma começa no canhão gravitacional e a outra começa na Torre do Conhecimento Quântico.","Riebeck disse que não tem como chegar ao observatório pela superfície (após tentar e falhar), mas provavelmente há uma trilha sob a crosta em algum lugar.","Há uma porta para o observatório na superfície, mas está quebrada.","O radar novo e mais sensível que os Nomai construíram nesse observatório foi incapaz de detectar qualquer traço do sinal do Olho."] },
    { id:"old-settlement", nome:"Antigo Assentamento", alias:["Assentamento Antigo","Old Settlement","Assentamento"],
      tipo:"Ruína", corpo:"Vale Incerto", orbita:4, nomai:"Ruínas", perigo:"Buraco negro", viajante:"Nenhum",
      desc:"O primeiro lugar onde os Nomai se instalaram depois de cair. Uma criança escreveu numa parede aqui.",
      dicas:["Fui o primeiro lugar onde eles se instalaram.","Casas pequenas de pedra, na superfície.","Uma criança escreveu numa parede aqui.","Fico perto de onde o primeiro pod caiu.","Fico no Vale Incerto."],
      diario:["Os sobreviventes Nomai que caíram no Vale Incerto desceram por um penhasco até um local para se abrigarem abaixo da superfície.","Os Nomai trabalharam juntos para recuperar um sinal com formato de um olho, que eles encontraram quando estavam a bordo do O Hospedeiro.","Os Nomai construíram um assentamento temporário abaixo do local da queda de sua cápsula de escape.","O sinal de certa forma era mais antigo que o próprio universo. Os Nomai decidiram chamá-lo de o \"Olho do Universo\".","Os Nomai abandonaram seu assentamento após uma crescente preocupação em relação a sua estabilidade."] },
    { id:"escape-pod-1", nome:"Cápsula de Escape 1", alias:["Pod de Fuga 1","Escape Pod 1","Pod 1","Cápsula de Fuga 1"],
      tipo:"Ruína", corpo:"Vale Incerto", orbita:4, nomai:"Ruínas", perigo:"Nenhum", viajante:"Nenhum",
      desc:"O pod que teve sorte: caiu num lugar onde o chão aguentou. Annona e Daz vieram nele.",
      dicas:["Fui o primeiro dos três a cair.","Quem saiu de mim teve sorte: o chão aguentou.","Annona e Daz vieram em mim.","Fico perto do assentamento antigo.","Fico na superfície do Vale Incerto."],
      diario:["Uma das três cápsulas de escape Nomai pousou em algum lugar do Vale Incerto.","Uma das três cápsulas de escape Nomai que caíram em nosso sistema solar.","Todas as três cápsulas de escape foram lançadas de algo chamado O Hospedeiro, que estava bem danificado."] },
    { id:"gravity-cannon-bh", nome:"Canhão Gravitacional", alias:["Canhão de Gravidade","Gravity Cannon","Canhão de gravidade do Vale Incerto"],
      tipo:"Estrutura", corpo:"Vale Incerto", orbita:4, nomai:"Sim", perigo:"Nenhum", viajante:"Nenhum",
      desc:"Lança e chama de volta ônibus Nomai. Tem um estacionado que pode te levar até a Lua Quântica.",
      dicas:["Disparo naves, não sondas.","Chamo um ônibus de volta de muito longe.","Existe um igual a mim em outro planeta.","Um ônibus Nomai estacionado aqui pode te levar até a lua que some.","Fico no Vale Incerto."],
      diario:["Eu recuperei uma exploradora Nomai da Lua Quântica.","Eu recuperei uma exploradora Nomai no Xereta.","Uma enorme estrutura cilíndrica que gera um forte campo gravitacional ascendente."] },
    { id:"riebeck-camp", nome:"Acampamento de Riebeck", alias:["Riebeck's Camp","Acampamento do Riebeck"],
      tipo:"Acampamento", corpo:"Vale Incerto", orbita:4, nomai:"Não", perigo:"Buraco negro", viajante:"Riebeck",
      desc:"Uma fogueira embaixo da crosta, um banjo e alguém que não quer voar de volta.",
      dicas:["Fico embaixo da crosta, num pedaço que ainda não caiu.","Um banjo toca aqui.","Quem acampa em mim não quer voltar voando.","Fico perto de um cruzamento de caminhos Nomai.","Riebeck está aqui."],
      diario:["Riebeck se dirigiu ao Vale Incerto para investigar o que os Nomai faziam no polo sul.","Riebeck aterrissou sua nave próximo à grande cúpula no polo sul. A porta que levava para dentro estava quebrada, então decidiu se dirigir ao norte, até as ruínas no equador, em busca de um caminho por baixo da superfície.","Riebeck descobriu um antigo caminho Nomai próximo ao acampamento no equador. O caminho começa dentro de um prédio em ruínas com árvores crescendo por lá.","Riebeck chegou até as Encruzilhadas e continuou a descer em busca de oxigênio.","Riebeck montou um acampamento no fundo das Encruzilhadas. Sua empolgação por estar em meio a tanta história Nomai só se compara ao medo que sente por buracos negros.","De todo o Recanto Lenhoso, só Riebeck se dedicou à arqueologia. Após superar seu medo do espaço e partir para o Vale Incerto a fim de explorar o imenso tesouro que é a cultura Nomai."] },

    // Luzeiro do Vale
    { id:"hollows-lantern", nome:"Luzeiro do Vale", alias:["Hollows Lantern","Lanterna","Hollow's Lantern","Lanterna do Vale"],
      tipo:"Lua", corpo:"Luzeiro do Vale", orbita:4, nomai:"Não", perigo:"Lava", viajante:"Nenhum",
      desc:"Lua vulcânica que bombardeia o Vale Incerto enquanto encolhe.",
      dicas:["Estou encolhendo.","Fico jogando pedras quentes no vizinho.","Sou uma lua, mas ninguém acampa em mim. Quente demais.","É por minha causa que o chão do planeta ao lado vive desabando.","Orbito o Vale Incerto."] },

    // Profundezas do Gigante
    { id:"giants-deep", nome:"Profundezas do Gigante", alias:["Giants Deep","Giant","Giant's Deep"],
      tipo:"Planeta", corpo:"Profundezas do Gigante", orbita:5, nomai:"Sim", perigo:"Ciclones", viajante:"Gabro",
      desc:"Oceano sem fim, ilhas que voam e ciclones. Gabro aprova.",
      dicas:["Minhas ilhas não ficam paradas no lugar.","Meus ciclones jogam tudo pro alto, inclusive você.","Pra chegar ao meu centro é preciso vencer uma corrente que empurra tudo pra fora.","Gabro fica numa rede olhando as minhas ondas.","Um canhão Nomai orbita em volta de mim."] },
    { id:"gabbro-island", nome:"Ilha de Gabro", alias:["Ilha de Gabro","Gabro's Island","Ilha do Gabro"],
      tipo:"Ilha", corpo:"Profundezas do Gigante", orbita:5, nomai:"Não", perigo:"Ciclones", viajante:"Gabro",
      desc:"Uma ilha com uma rede e uma flauta. De vez em quando vai parar no espaço.",
      dicas:["Uma ilha com uma rede.","De vez em quando, vou parar no espaço.","Uma flauta toca aqui.","Quem mora em mim também lembra dos loops.","Fico nas Profundezas do Gigante."],
      diario:["Hal disse que Gabro voltou ao Profundezas do Gigante para tentar aprender mais sobre a estátua Nomai do observatório.","Gabro está descansando numa rede na praia da ilha.","Gabro encontrou a estátua Nomai em outra ilha. Os olhos da estátua começaram a brilhar e Gabro viu suas memórias sendo reproduzidas diante de seus olhos.","Gabro se lembra de ter morrido. Viu suas memórias sendo reproduzidas diante de seus olhos, assim como ocorreu naquela vez com a estátua.","Parece que só eu e Gabro estamos conscientes de que estamos em um loop temporal."] },
    { id:"statue-island", nome:"Ilha da Estátua", alias:["Statue Island","Oficina de Estátuas","Statue Workshop"],
      tipo:"Ilha", corpo:"Profundezas do Gigante", orbita:5, nomai:"Sim", perigo:"Ciclones", viajante:"Nenhum",
      desc:"A oficina onde os Nomai faziam máscaras de pedra que gravam memórias. Uma delas está no museu.",
      dicas:["Aqui se faziam máscaras de pedra que gravam memórias.","Tenho uma oficina inteira dedicada a estátuas.","Foi daqui que veio a estátua do museu.","Tenho uma estátua enorme quebrada na costa.","Fico nas Profundezas do Gigante."],
      diario:["Uma das ilhas no Profundezas do Gigante tem uma estátua Nomai na praia, assim como a que Gabro trouxe para o Recanto Lenhoso.","A Ilha da Estátua (como Gabro a chama) é aquela com duas ilhas conectadas por um arco de pedra.","A ilha deve ser onde os Nomai criavam estátuas como aquela do nosso observatório.","Encontrei uma estátua Nomai na praia. Se parece como a que temos no observatório.","Encontrei uma placa de “Oficina de Estátuas” próxima a uma porta quebrada que levava para dentro da ilha.","Algumas crianças Nomai discutiram sobre contornar a porta da Oficina De Estátuas e dar uma olhadinha lá dentro por meio de uma rota alternativa (e mais perigosa)."] },
    { id:"construction-yard", nome:"Estaleiro de Construção", alias:["Ilha do Estaleiro","Construction Yard","Estaleiro"],
      tipo:"Ilha", corpo:"Profundezas do Gigante", orbita:5, nomai:"Sim", perigo:"Ciclones", viajante:"Nenhum",
      desc:"A ilha onde o Canhão de Sonda foi construído. Cassava e Mallow discutiram muito aqui.",
      dicas:["Aqui se construiu algo pra ser lançado.","Cassava e Mallow discutiram por minha causa.","Sou uma ilha com guindastes e um espaço vazio no meio.","O que foi feito aqui está em órbita agora.","Fico nas Profundezas do Gigante."],
      diario:["Aqui é a ilha onde os Nomai construíram o Canhão de Sonda Orbital.","Por algum motivo, os Nomai colocaram o Canhão de Sonda Orbital num intervalo por tempo indeterminado. Não mandaram o canhão disparar.","De acordo com um computador Nomai, uma sonda de longo alcance foi recentemente lançada do Canhão de Sonda Orbital.","Os Nomai construíram o Canhão de Sonda Orbital no Estaleiro de Construção, no Profundezas do Gigante."] },
    { id:"bramble-island", nome:"Ilha do Abrolho", alias:["Ilha do Espinheiro","Bramble Island","Ilha Bramble"],
      tipo:"Ilha", corpo:"Profundezas do Gigante", orbita:5, nomai:"Não", perigo:"Peixe-pescador", viajante:"Nenhum",
      desc:"Uma ilha com uma semente do Abrolho Sombrio que cresceu demais. Por dentro, é outro mundo.",
      dicas:["Uma ilha com algo que não deveria estar aqui.","Uma semente cresceu demais em mim.","Por dentro, é como estar em outro planeta.","Dá pra usar pra chegar num lugar cheio de névoa sem levar a nave.","Fico nas Profundezas do Gigante."] },
    { id:"quantum-island", nome:"Torre dos Julgamentos Quânticos", alias:["Tower of Quantum Trials","Ilha Quântica","Quantum Island","Torre das Provações Quânticas"],
      tipo:"Torre", corpo:"Profundezas do Gigante", orbita:5, nomai:"Sim", perigo:"Ciclones", viajante:"Nenhum",
      desc:"Uma torre numa ilha que às vezes não está lá. Ensina o básico sobre coisas que somem.",
      dicas:["Ensino a primeira lição sobre coisas que somem.","Fico numa ilha que às vezes não está lá.","Tenho um santuário pra fazer as coisas mudarem de lugar.","Minha ilha vai e volta, como a lua.","Fico nas Profundezas do Gigante."],
      diario:["Os Nomai detectaram um sinal quântico vindo de algum lugar no Profundezas do Gigante.","Essa torre guarda o conhecimento que um Nomai precisava para fazer sua primeira jornada quântica.","“Analisar um objeto quântico; analisar a imagem de um objeto quântico. Resulta no mesmo.”","Os Nomai a chamaram de “Lei do Pensamento Quântico”.","“Lembre-se, os demais fragmentos quânticos também têm lições a ensinar”."] },
    { id:"probe-tracking-module", nome:"Módulo de Rastreamento de Sonda", alias:["Módulo de Rastreamento da Sonda","Probe Tracking Module","Módulo de Rastreamento"],
      tipo:"Estrutura", corpo:"Profundezas do Gigante", orbita:5, nomai:"Sim", perigo:"Correnteza", viajante:"Nenhum",
      desc:"Caiu do canhão e afundou até o núcleo. Guarda o registro de milhões de disparos.",
      dicas:["Caí do céu e afundei.","Guardo o registro de milhões de disparos.","Mostro onde a sonda finalmente achou o que procurava.","Estou no fundo do oceano, dentro do núcleo.","Fico nas Profundezas do Gigante."],
      diario:["Um dos três módulos do Canhão de Sonda Orbital.","O Módulo de Rastreamento de Sonda está recebendo dados da sonda lançada.","Qualquer Nomai a bordo do Módulo de Rastreamento de Sonda seria o primeiro a ver as coordenadas do Olho do universo.","Um computador Nomai informou que o Módulo de Rastreamento de Sonda consta como “desaparecido”.","Eu vi o Módulo de Rastreamento de Sonda através de uma piscina de projeção Nomai. Parece que o Módulo está submerso. Pude ver eletricidade roxa por fora da janela de visualização.","O Canhão de Sonda Orbital lançou milhões de sondas."] },
    { id:"ocean-core", nome:"Profundezas do Oceano", alias:["Núcleo das Profundezas do Gigante","Ocean Core","Núcleo do Oceano","Núcleo"],
      tipo:"Núcleo", corpo:"Profundezas do Gigante", orbita:5, nomai:"Não", perigo:"Correnteza", viajante:"Nenhum",
      desc:"O centro oco do oceano, protegido por uma corrente que empurra tudo pra fora. Águas-vivas ajudam a passar.",
      dicas:["Uma corrente forte empurra tudo pra longe de mim.","Uma água-viva serve de escudo pra chegar aqui.","Tenho corais gigantes e uma escuridão molhada.","Nada elétrico funciona direito perto das minhas guardiãs.","Fico no fundo das Profundezas do Gigante."],
      diario:["Os Nomai no Estaleiro de Construção viram algo afundar por baixo da correnteza subaquática, o que eles antes achavam impossível.","Passei por uma barreira elétrica e alcancei a floresta de corais no núcleo do planeta.","Gabro disse que há uma forte correnteza por baixo da superfície do oceano que evita que qualquer coisa afunde ali.","Feldspato encontrou um jeito de alcançar o núcleo do Profundezas do Gigante.","O oceano é surpreendente calmo por baixo da correnteza. Algum tipo de campo elétrico reveste o núcleo do planeta."] },
    { id:"probe-cannon", nome:"Canhão de Sonda Orbital", alias:["Canhão de Sonda","Probe Cannon","Cannon","Orbital Probe Cannon"],
      tipo:"Estação", corpo:"Profundezas do Gigante", orbita:5, nomai:"Sim", perigo:"Vácuo", viajante:"Nenhum",
      desc:"Canhão Nomai em órbita das Profundezas do Gigante. Dispara uma vez por ciclo e se parte no processo.",
      dicas:["Disparo uma vez por ciclo.","Uma parte minha já se desprendeu.","Fui construído pra achar um lugar que ninguém conseguia ver.","Orbito o planeta oceânico.","Meu Módulo de Rastreamento afundou no oceano lá embaixo."],
      diario:["Utilizei uma piscina de projeção Nomai e vi o interior de uma estação espacial orbitando o Profundezas do Gigante.","Gabro vê uma luz brilhante no céu no início de cada loop. Algo deve estar acontecendo na órbita do Profundezas do Gigante.","Os restos quebrados de uma estação espacial Nomai orbitando o Profundezas do Gigante. Há três caminhos de acesso partindo da área de comando central.","Os Nomai finalizaram a construção do módulo final do Canhão de Sonda Orbital e o colocaram em órbita em torno do Profundezas do Gigante.","Os Nomai decidiram construir um canhão de sonda para orbitar o Profundezas do Gigante.","O Canhão de Sonda Orbital foi criado para encontrar a localização exata do Olho do Universo."] },

    // Abrolho Sombrio
    { id:"dark-bramble", nome:"Abrolho Sombrio", alias:["Bramble","Dark Bramble","Espinheiro Sombrio"],
      tipo:"Planeta", corpo:"Abrolho Sombrio", orbita:6, nomai:"Ruínas", perigo:"Peixe-pescador", viajante:"Feldspato",
      desc:"Névoa, raízes e peixes-pescadores. Maior por dentro do que por fora.",
      dicas:["Meus sons viajam longe demais.","Quem entra em mim raramente sai.","Sou maior por dentro do que por fora.","Desligue os motores e fique em silêncio ao passar pelos meus moradores.","Feldspato se perdeu aqui dentro."] },
    { id:"feldspar-camp", nome:"Acampamento de Feldspato", alias:["Acampamento de Feldspato","Feldspato's Camp","Acampamento do Feldspato"],
      tipo:"Acampamento", corpo:"Abrolho Sombrio", orbita:6, nomai:"Não", perigo:"Peixe-pescador", viajante:"Feldspato",
      desc:"Uma fogueira dentro de um lugar sem tamanho, com uma gaita tocando baixinho.",
      dicas:["Fico dentro de um espaço que não obedece o tamanho de fora.","Uma gaita toca bem baixinho aqui.","Quem acampa em mim foi dado como morto.","Pra chegar, é preciso seguir o som certo.","Feldspato está aqui."],
      diario:["Quando lanço meu batedor dentro da semente que caiu no Recanto Lenhoso, ele acaba indo parar em um espaço bem maior, repleto de névoa e vinhas espinhentas.","Feldspato se dirigiu ao Abrolho Sombrio após chegar até o núcleo do Profundezas do Gigante.","Feldspato não morreu! Sua nave caiu e agora está acampando dentro de um enorme esqueleto de tamboril.","Feldspato não acha que o radar do meu batedor está errado quando mostra que meu batedor está em dois lugares ao mesmo tempo. Sua teoria é de que o espaço não funciona do mesmo jeito dentro do Abrolho Sombrio.","Feldspato não demonstra nenhum desejo de retornar à civilização. Tem aproveitado muito a paz e a quietude (relativas) de lá."] },
    { id:"escape-pod-3", nome:"Cápsula de Escape 3", alias:["Pod de Fuga 3","Escape Pod 3","Pod 3","Cápsula de Fuga 3"],
      tipo:"Ruína", corpo:"Abrolho Sombrio", orbita:6, nomai:"Ruínas", perigo:"Peixe-pescador", viajante:"Nenhum",
      desc:"O pod que não teve sorte. Caiu num lugar de onde ninguém sai, e quem saiu deixou uma trilha de luz.",
      dicas:["Fui o que não teve tanta sorte.","Caí num lugar de onde ninguém consegue sair.","Quem saiu de mim foi a pé, no escuro, e deixou uma trilha de luz.","Bells estava aqui.","Fico no Abrolho Sombrio."],
      diario:["Uma das três cápsulas de escape Nomai nunca conseguiu sair do Abrolho Sombrio.","Uma das três cápsulas de escape Nomai que caíram em nosso sistema solar.","Todas as três cápsulas de escape foram lançadas de algo chamado O Hospedeiro, que estava bem danificado.","Os sobreviventes da cápsula de escape 3 encontraram dois sinalizadores diferentes vindo do O Hospedeiro, como se estivesse em dois lugares ao mesmo tempo.","Sobreviventes da Cápsula de Escape 3"] },
    { id:"nomai-grave", nome:"Túmulo Nomai", alias:["Nomai Grave","Sepultura Nomai"],
      tipo:"Ruína", corpo:"Abrolho Sombrio", orbita:6, nomai:"Ruínas", perigo:"Peixe-pescador", viajante:"Nenhum",
      desc:"O fim da trilha de luzes que sai do Pod 3. Um lugar silencioso, cheio de ossos e um registro importante.",
      dicas:["Sou o fim de uma trilha de luzes.","Um lugar silencioso, cheio de ossos.","Um registro aqui mostra de onde eles vieram.","Não sou bem um túmulo, mas foi onde ficaram.","Fico no Abrolho Sombrio."],
      diario:["Os sobreviventes da cápsula de escape 3 abandonaram os destroços e tentaram retornar ao O Hospedeiro.","Os sobreviventes decidiram seguir o sinalizador mais próximo do O Hospedeiro, devido ao suprimento limitado de ar. Eles planejaram deixar um rastro de luzes pelo caminho caso alguém respondesse ao sinal de socorro.","Os sobreviventes da Cápsula de Escape 3 seguiram um dos dois sinalizadores emitidos pelo O Hospedeiro até uma pequena semente do Abrolho Sombrio, por onde não conseguiram mais avançar.","O sinalizador do O Hospedeiro estava se esvaindo e logo não existiria mais.","Os Nomai mal conseguiram captar o sinalizador do O Hospedeiro dentro da semente, mas a abertura era muito pequena para um único Nomai passar, muito menos uma cápsula de escape.","Se eu lançar meu batedor na semente, poderei tirar fotos de uma enorme nave Nomai abandonada."] },
    { id:"vessel", nome:"O Hospedeiro", alias:["Hospedeiro","Vessel","Nave Nomai","A Nave","The Vessel"],
      tipo:"Nave", corpo:"Abrolho Sombrio", orbita:6, nomai:"Sim", perigo:"Peixe-pescador", viajante:"Nenhum",
      desc:"A nave Nomai que trouxe todos pra cá, presa nas raízes do Abrolho Sombrio.",
      dicas:["Estou parada há muito, muito tempo.","Trouxe um povo inteiro até este sistema.","Estou presa em raízes, cercada de névoa.","Meu núcleo de dobra queimou e nunca mais decolei.","Escall e a tripulação atenderam por mim a um sinal mais antigo que o universo."],
      diario:["Eu lancei meu batedor na semente no Túmulo Nomai e tirei fotos de uma enorme nave Nomai abandonada.","Os Nomai se transportaram para esse sistema solar em uma espaçonave chamada o Hospedeiro. Eles tentaram seguir o sinal vindo do Olho do Universo.","O Hospedeiro caiu em algum lugar no Abrolho sombrio.","O núcleo de transportação do O Hospedeiro se quebrou com a queda da nave no Abrolho Sombrio.","Encontrei o Hospedeiro Nomai abandonado bem dentro do Abrolho Sombrio.","O núcleo de transportação do O Hospedeiro já morreu há muito tempo."] },

    // Xereta
    { id:"interloper", nome:"Xereta", alias:["Cometa","O Intruso","The Interloper","Interloper"],
      tipo:"Cometa", corpo:"Xereta", orbita:7, nomai:"Ruínas", perigo:"Matéria fantasma", viajante:"Nenhum",
      desc:"Cometa gelado com um passageiro mortal escondido no núcleo.",
      dicas:["Sou só um visitante de passagem.","Tenho gelo por fora e algo bem pior por dentro.","Minha órbita é longa e me leva quase até o Sol.","Carreguei a razão de um povo inteiro ter sumido.","Dois Nomai vieram me investigar e não voltaram."] },
    { id:"interloper-core", nome:"Núcleo Rompido", alias:["Núcleo do Xereta","Interloper Core","Núcleo do Cometa","Fissura do Xereta"],
      tipo:"Núcleo", corpo:"Xereta", orbita:7, nomai:"Ruínas", perigo:"Matéria fantasma", viajante:"Nenhum",
      desc:"O interior do cometa, só acessível quando o gelo derrete perto do Sol. Dois Nomai congelados esperam lá.",
      dicas:["Só se chega em mim quando o gelo derrete, perto do Sol.","Dois Nomai congelados esperam aqui.","É de mim que saiu a coisa que matou todo mundo.","Tenho uma fissura por onde tudo escapou.","Fico dentro do cometa."],
      diario:["O equipamento da exploradora captou estranhas leituras vindas de algum lugar sob a superfície.","Duas das Nomai localizaram a fissura no gelo no lado ensolarado do Xereta. Elas desceram até lá dentro para investigar.","Encontrei as duas integrantes da tripulação, da exploradora Nomai, próximo de uma rocha quebrada, que parece ter se implodido.","As Nomai rastrearam as estranhas leituras de energia até uma pedra esférica que cobria alguma forma de matéria exótica.","Elas determinaram que a matéria exótica fosse letal e estava sob extrema pressão. Se a pedra se rompesse, a matéria ali contida iria se expandir rapidamente, apagando quase que completamente o sistema solar.","Uma das Nomai ficou para trás para analisar a matéria alienígena enquanto a outra retornou à superfície para alertar os demais Nomai."] },
    { id:"nomai-shuttle", nome:"Exploradora Nomai Congelada", alias:["Ônibus Nomai do Xereta","Nomai Shuttle","Ônibus Nomai","Shuttle"],
      tipo:"Nave", corpo:"Xereta", orbita:7, nomai:"Sim", perigo:"Nenhum", viajante:"Nenhum",
      desc:"O veículo que Poke e Clary usaram pra chegar ao cometa. Continua estacionado lá.",
      dicas:["Sou um veículo pequeno, estacionado num visitante gelado.","Fui trazido por dois cientistas curiosos.","Dá pra me chamar de volta com um canhão de gravidade.","Estou parado na superfície de um cometa.","Poke e Clary vieram em mim."],
      diario:["Encontrei uma exploradora Nomai quase que completamente congelada.","Os Nomai pousaram no Xereta logo após a sua chegada ao nosso sistema solar. O equipamento da exploradora captou estranhas leituras vindas de algum lugar sob a superfície.","Havia três Nomai a bordo da exploradora. Uma delas ficou para trás para manter a exploradora aquecida enquanto as outras duas exploraram o Xereta.","Clary, a Nomai que ficou para trás, perdeu contato com as outras duas assim que desceram abaixo da superfície do Xereta."] },

    // Estação do Buraco Branco
    { id:"white-hole-station", nome:"Estação do Buraco Branco", alias:["Estação Buraco Branco","White Hole","White Hole Station"],
      tipo:"Estação", corpo:"Estação do Buraco Branco", orbita:8, nomai:"Sim", perigo:"Nenhum", viajante:"Nenhum",
      desc:"Onde você aparece depois de cair no buraco negro. Tem caminho de volta.",
      dicas:["Você provavelmente chegou aqui sem querer.","Estou do outro lado de um buraco.","Fico no limite do sistema, longe de tudo.","Sirvo de rota de volta pra quem caiu.","Meu núcleo de dobra te devolve pro Vale Incerto."],
      diario:["Muitos Nomai retornaram à estação para investigar a leitura do equipamento que registrava uma violação à causalidade.","Todas as torres de translação Nomai estão sintonizadas a um corpo astral específico.","Para usar uma torre, você precisa estar sobre a plataforma durante o alinhamento da torre com seu corpo astral correspondente (o alinhamento ocorre quando o corpo astral está diretamente acima de você).","Há uma Estação do Buraco Branco do lado oposto ao buraco negro do Vale Incerto.","Os experimentos no Laboratório de Alta Energia foram baseados em achados surpreendentes da Estação do Buraco Branco.","As torres no Gêmeo Cinzento foram feitas no molde da Estação do Buraco Branco."] },

    // Lua Quântica
    { id:"quantum-moon", nome:"Lua Quântica", alias:["Quantum","Quantum Moon"],
      tipo:"Lua", corpo:"Lua Quântica", orbita:null, nomai:"Sim", perigo:"Nenhum", viajante:"Solanum",
      desc:"A lua que só existe onde alguém observa. Solanum espera lá.",
      dicas:["Só estou onde alguém está olhando.","Visito cinco lugares, e um sexto que ninguém vê.","Tenho um santuário no meu polo sul.","Alguém ainda está aqui em cima esperando visita.","Solanum mora aqui."],
      diario:["Os Nomai no Vale Incerto observaram a lua fantasma que às vezes aparece no céu.","Os Nomai no Gêmeo Cálido observaram a lua que desaparecia quando ninguém a via.","Encontrei uma Nomai morta usando traje espacial no polo sul.","Uma Nomai chamada Solanum aterrissou sua exploradora na Lua Quântica.","As anotações de pesquisa de Cherte mencionam uma Lua Quântica que os Lenhosos nunca conseguiram pousar.","Fui capaz de aterrissar na superfície da Lua Quântica."] },
    { id:"quantum-shrine", nome:"Templo Quântico", alias:["Santuário Quântico","Quantum Shrine","Santuário"],
      tipo:"Estrutura", corpo:"Lua Quântica", orbita:null, nomai:"Sim", perigo:"Nenhum", viajante:"Nenhum",
      desc:"O santuário no polo sul da Lua Quântica. Feche a porta, apague a luz e olhe de novo.",
      dicas:["Sirvo pra viajar sem sair do lugar.","Feche a porta, apague a luz e olhe de novo.","Fico no polo sul de uma lua que anda.","Sou a chave pra chegar ao sexto lugar.","Fico na Lua Quântica."],
      diario:["“Lembre-se da lei da sexta localização” está inscrito próximo a um mural de uma torre suspensa sobre um buraco negro.","Os Nomai construíram um templo na Lua Quântica para ajudá-los na peregrinação até a sexta localização.","Um templo Nomai que vaga em volta da Lua Quântica.","“Você se lembrou da lei do pensamento quântico” está inscrito próximo a um mural de uma torre na ilha.","“Lembre-se da lei da confusão quântica” está inscrito próximo a um mural de um fragmento quântico na caverna."] },

    // DLC (Echoes of the Eye)
    { id:"stranger", nome:"O Desconhecido", alias:["O Estranho","Stranger","Forasteiro","The Stranger","Estranho"], dlc:true,
      tipo:"Nave", corpo:"O Desconhecido", orbita:9, nomai:"Não", perigo:"Escuridão", viajante:"Nenhum",
      desc:"Um anel escondido na luz do Sol, cheio de água, escuridão e segredos. (Echoes of the Eye)",
      dicas:["Você não me vê, mas eu estou lá.","Por fora sou só uma sombra no Sol. Por dentro, um rio inteiro.","Meus habitantes vieram de longe pra silenciar um sinal.","Meus moradores dormem e sonham num lugar sem luz.","Cheguei junto com a expansão Echoes of the Eye."] }
  ];

  // Colunas da grade. type:"num" compara e mostra seta; near = grupos que dão "parcial".
  const COLS_LOCAIS = [
    { k:"tipo",     l:"Tipo" },
    { k:"corpo",    l:"Corpo",  title:"Corpo celeste onde fica",
      near:[["Recanto Lenhoso","Pedra de Lia"],["Gêmeo Cálido","Gêmeo Cinzento"],["Vale Incerto","Luzeiro do Vale"],["Profundezas do Gigante"],["Sol"]] },
    { k:"orbita",   l:"Órbita", type:"num", title:"Posição do corpo a partir do Sol" },
    { k:"nomai",    l:"Nomai",  near:[["Sim","Ruínas"]] },
    { k:"perigo",   l:"Perigo" },
    { k:"viajante", l:"Viajante" }
  ];

  // PERSONAGENS: local precisa ser o nome de um item de LOCAIS (o build confere).
  //   status é no começo do ciclo. dicas: 2 frases, liberadas junto com as dicas extras.
  const PERSONAGENS = [
    // Lenhosos
    { id:"slate", nome:"Ardósia", alias:["Ardósia"], especie:"Lenhoso", local:"Recanto Lenhoso", papel:"Engenharia", instrumento:"Nenhum", status:"Vivo",
      desc:"Construiu a sua nave (e quase todas as outras) e garante que o para-brisa aguenta.",
      dicas:["Fica perto da plataforma de lançamento, sempre mexendo em alguma coisa.","Se algo quebrar na sua nave, a culpa é de quem construiu."] },
    { id:"hornfels", nome:"Corneana", alias:["Corneana"], especie:"Lenhoso", local:"Recanto Lenhoso", papel:"Liderança", instrumento:"Nenhum", status:"Vivo",
      desc:"Comanda a Outer Wilds Ventures do alto do observatório.",
      dicas:["Fica no observatório, orgulhoso da exposição.","Coordena todo o programa espacial da vila."] },
    { id:"gossan", nome:"Gossan", especie:"Lenhoso", local:"Recanto Lenhoso", papel:"Instrução", instrumento:"Nenhum", status:"Vivo",
      desc:"Te ensinou a pilotar e ainda te lembra de usar o cinto.",
      dicas:["Fica ao lado da caverna de gravidade zero.","Foi quem te ensinou a voar."] },
    { id:"hal", nome:"Hal", especie:"Lenhoso", local:"Recanto Lenhoso", papel:"Curadoria", instrumento:"Nenhum", status:"Vivo",
      desc:"Cuida do museu e é seu melhor amigo desde criança.",
      dicas:["Passa o dia no museu, empolgado com a peça nova.","Fica ao lado da estátua Nomai que acabou de chegar."] },
    { id:"gneiss", nome:"Gneiss", especie:"Lenhoso", local:"Recanto Lenhoso", papel:"Música", instrumento:"Banjo", status:"Vivo",
      desc:"Fez os instrumentos de todos os viajantes e toca perto da fogueira.",
      dicas:["Toca na parte alta da vila, perto de uma fogueira.","Construiu o banjo, a flauta, o tambor e a gaita dos exploradores."] },
    { id:"chert", nome:"Cherte", alias:["Cherte"], especie:"Lenhoso", local:"Gêmeo Cálido", papel:"Viajante", instrumento:"Tambor", status:"Vivo",
      desc:"Astrônomo do grupo. Acampa no topo do Gêmeo Cálido e percebe que as estrelas estão morrendo.",
      dicas:["Acampa numa cratera no topo de um planeta de areia.","Observa as estrelas com uma preocupação que só cresce."] },
    { id:"esker", nome:"Esker", especie:"Lenhoso", local:"Pedra de Lia", papel:"Viajante", instrumento:"Assobio", status:"Vivo",
      desc:"Cuida do posto de observação lunar e reclama que ninguém visita.",
      dicas:["É o único morador de uma lua.","Não precisa de instrumento: assobia."] },
    { id:"riebeck", nome:"Riebeck", especie:"Lenhoso", local:"Vale Incerto", papel:"Viajante", instrumento:"Banjo", status:"Vivo",
      desc:"Ama arqueologia Nomai. Odeia voar.",
      dicas:["Acampou embaixo da crosta de um planeta que está desabando.","Adora ruínas, mas morre de medo da viagem de volta."] },
    { id:"gabbro", nome:"Gabro", alias:["Gabro"], especie:"Lenhoso", local:"Profundezas do Gigante", papel:"Viajante", instrumento:"Flauta", status:"Vivo",
      desc:"Deitado numa rede, olhando as ondas. Também lembra dos loops, mas não se estressa.",
      dicas:["Fica numa rede, numa ilha que não para no lugar.","É a única outra pessoa que lembra do que aconteceu no ciclo anterior."] },
    { id:"feldspar", nome:"Feldspato", alias:["Feldspato"], especie:"Lenhoso", local:"Abrolho Sombrio", papel:"Viajante", instrumento:"Gaita", status:"Vivo",
      desc:"Primeira pessoa a voar. Sumiu há anos, mas segue firme lá dentro.",
      dicas:["Todo mundo na vila acha que morreu.","Acampou dentro de um lugar cheio de névoa e raízes."] },
    { id:"tephra", nome:"Tefra", alias:["Tefra"], especie:"Lenhoso", local:"Recanto Lenhoso", papel:"Criança", instrumento:"Nenhum", status:"Vivo",
      desc:"Comanda a brincadeira de esconde-esconde na vila.",
      dicas:["Te desafia a achar os amigos escondidos.","Fica perto da entrada da vila."] },
    { id:"galena", nome:"Galena", especie:"Lenhoso", local:"Recanto Lenhoso", papel:"Criança", instrumento:"Nenhum", status:"Vivo",
      desc:"Está escondida em algum lugar da vila. Boa sorte.",
      dicas:["Participa do esconde-esconde.","Você só acha com o telescópio de sinais."] },
    { id:"mica", nome:"Mica", especie:"Lenhoso", local:"Recanto Lenhoso", papel:"Criança", instrumento:"Nenhum", status:"Vivo",
      desc:"Te empresta uma nave de brinquedo pra treinar pouso.",
      dicas:["Tem um brinquedo que voa de verdade.","Fica perto da plataforma de lançamento."] },
    { id:"moraine", nome:"Moraina", alias:["Moraina"], especie:"Lenhoso", local:"Recanto Lenhoso", papel:"Criança", instrumento:"Nenhum", status:"Vivo",
      desc:"Fica no alto com o telescópio de sinais, ouvindo a música dos viajantes.",
      dicas:["Adora ouvir os viajantes de longe.","Fica num ponto alto da vila com um telescópio de sinais."] },
    { id:"arkose", nome:"Arcose", alias:["Arcose"], especie:"Lenhoso", local:"Recanto Lenhoso", papel:"Criança", instrumento:"Nenhum", status:"Vivo",
      desc:"Mais uma criança escondida pela vila.",
      dicas:["Participa do esconde-esconde.","Se esconde num lugar alto."] },
    { id:"marl", nome:"Marga", alias:["Marga"], especie:"Lenhoso", local:"Recanto Lenhoso", papel:"Ofício", instrumento:"Nenhum", status:"Vivo",
      desc:"Quer derrubar a árvore gigante no meio da vila. Ninguém deixa.",
      dicas:["Anda com um machado e um plano.","Tem uma opinião forte sobre a árvore da vila."] },
    { id:"spinel", nome:"Espinela", alias:["Espinela"], especie:"Lenhoso", local:"Recanto Lenhoso", papel:"Ofício", instrumento:"Nenhum", status:"Vivo",
      desc:"Pesca ao lado da vila e não pega muita coisa.",
      dicas:["Fica com uma vara na mão, perto da água.","A paciência é maior que o resultado."] },
    { id:"porphy", nome:"Pórfiro", alias:["Pórfiro"], especie:"Lenhoso", local:"Recanto Lenhoso", papel:"Ofício", instrumento:"Nenhum", status:"Vivo",
      desc:"Faz uma bebida com seiva da árvore e insiste pra você provar.",
      dicas:["Produz algo com seiva de árvore.","Fica perto de barris na vila."] },
    { id:"tektite", nome:"Tektite", especie:"Lenhoso", local:"Recanto Lenhoso", papel:"Ofício", instrumento:"Nenhum", status:"Vivo",
      desc:"Trabalha na mina e sabe onde tem matéria fantasma.",
      dicas:["Fica na entrada de uma mina.","Avisa sobre um perigo invisível lá dentro."] },

    // Nomai
    { id:"solanum", nome:"Solanum", especie:"Nomai", local:"Lua Quântica", papel:"Peregrina", instrumento:"Nenhum", status:"Vivo",
      desc:"A última Nomai que você pode encontrar. Se olhar no lugar certo.",
      dicas:["Está esperando visita num lugar que muda de lugar.","Conversa com você escrevendo no chão."] },
    { id:"poke", nome:"Poke", especie:"Nomai", local:"Gêmeo Cinzento", papel:"Cientista", instrumento:"Nenhum", status:"Morto",
      desc:"Projetou os núcleos de dobra e o Projeto do Gêmeo Cinzento.",
      dicas:["Especialista em dobra espacial.","Foi investigar o cometa junto com Clary."] },
    { id:"pye", nome:"Pye", especie:"Nomai", local:"Estação Solar", papel:"Cientista", instrumento:"Nenhum", status:"Morto",
      desc:"Direta ao ponto: se o Sol não coopera, a gente ajuda ele a explodir.",
      dicas:["Trabalhou no Laboratório de Alta Energia.","Escreveu com raiva que a Estação Solar era um fracasso."] },
    { id:"clary", nome:"Clary", especie:"Nomai", local:"Estação Solar", papel:"Cientista", instrumento:"Nenhum", status:"Morto",
      desc:"Trabalhou na Estação Solar e foi investigar o cometa com Poke.",
      dicas:["Ajudou a construir a Estação Solar.","Ficou congelada dentro de um cometa."] },
    { id:"cassava", nome:"Cassava", especie:"Nomai", local:"Profundezas do Gigante", papel:"Cientista", instrumento:"Nenhum", status:"Morto",
      desc:"Trabalhou no Canhão de Sonda e tinha certeza de que Mallow ia explodir tudo.",
      dicas:["Se preocupava com a potência de um disparo.","Trabalhou no Estaleiro de Construção."] },
    { id:"mallow", nome:"Mallow", especie:"Nomai", local:"Profundezas do Gigante", papel:"Cientista", instrumento:"Nenhum", status:"Morto",
      desc:"Queria disparar o canhão na potência máxima. Conseguiu.",
      dicas:["Discutiu com Cassava sobre o canhão.","Ganhou a discussão. O canhão perdeu um pedaço."] },
    { id:"daz", nome:"Daz", especie:"Nomai", local:"Vale Incerto", papel:"Criança", instrumento:"Nenhum", status:"Morto",
      desc:"Chegou no pod de fuga ainda criança e cresceu vendo a cidade ser construída.",
      dicas:["Escreveu na parede do assentamento antigo quando era criança.","Veio no primeiro pod de fuga."] },
    { id:"coleus", nome:"Coleus", especie:"Nomai", local:"Gêmeo Cálido", papel:"Criança", instrumento:"Nenhum", status:"Morto",
      desc:"Sumiu de vista ao apagar a luz numa caverna quântica. E descobriu uma regra.",
      dicas:["Desapareceu numa caverna quando a luz apagou.","Ajudou a descobrir como se mover junto com uma pedra quântica."] },
    { id:"melorae", nome:"Melorae", especie:"Nomai", local:"Gêmeo Cálido", papel:"Cientista", instrumento:"Nenhum", status:"Morto",
      desc:"Estudou as cavernas quânticas ao lado de Coleus.",
      dicas:["Pesquisou pedras que mudam de lugar.","Registrou o que aconteceu com Coleus."] },
    { id:"escall", nome:"Escall", especie:"Nomai", local:"O Hospedeiro", papel:"Liderança", instrumento:"Nenhum", status:"Morto",
      desc:"Comandava a nave que respondeu ao sinal do Olho. Nunca saiu do Abrolho Sombrio.",
      dicas:["Decidiu seguir um sinal mais antigo que o universo.","Ficou na nave depois que os pods de fuga partiram."] },
    { id:"filix", nome:"Filix", especie:"Nomai", local:"Gêmeo Cálido", papel:"Exploração", instrumento:"Nenhum", status:"Morto",
      desc:"Sobreviveu ao pouso do Pod 2 e abriu caminho pelas cavernas.",
      dicas:["Veio no segundo pod de fuga.","Explorou cavernas de areia em busca de um lugar seguro."] },
    { id:"annona", nome:"Annona", especie:"Nomai", local:"Vale Incerto", papel:"Liderança", instrumento:"Nenhum", status:"Morto",
      desc:"Veio no Pod 1 e organizou os sobreviventes no assentamento antigo.",
      dicas:["Guiou os sobreviventes do primeiro pod.","Se preocupava com quem estava no terceiro pod."] },
    { id:"bells", nome:"Bells", especie:"Nomai", local:"Abrolho Sombrio", papel:"Exploração", instrumento:"Nenhum", status:"Morto",
      desc:"Saiu do Pod 3 a pé, no escuro, deixando uma trilha de luzes pra quem viesse depois.",
      dicas:["Veio no pod que caiu no pior lugar possível.","Deixou um caminho de luzes pra guiar os outros."] },

    // DLC
    { id:"prisioneiro", nome:"Prisioneiro", alias:["Prisoner","The Prisoner","O Prisioneiro"], especie:"Outro", local:"O Desconhecido", papel:"Prisioneiro", instrumento:"Nenhum", status:"Vivo", dlc:true,
      desc:"Trancado há eras por ter feito o que achou certo. (Echoes of the Eye)",
      dicas:["Está preso há mais tempo do que qualquer um consegue lembrar.","Se comunica sem palavras, com uma lanterna."] }
  ];

  const COLS_PERSONAGENS = [
    { k:"especie",     l:"Espécie" },
    { k:"local",       l:"Local" },
    { k:"papel",       l:"Papel" },
    { k:"instrumento", l:"Instrumento" },
    { k:"status",      l:"Status" }
  ];

  return { LOCAIS, COLS_LOCAIS, PERSONAGENS, COLS_PERSONAGENS };
})();
