// Conteúdo do jogo. Depois de editar, rode: node tools/build.js
window.OUTERDLE_DATA = (() => {
  "use strict";

  // LOCAIS
  //   corpo    corpo celeste onde fica (planetas/luas apontam pra si mesmos)
  //   orbita   posição a partir do Sol; null = varia (Lua Quântica)
  //   nomai    "Sim" (estrutura ativa), "Ruínas" ou "Não"
  //   viajante quem acampa ali
  //   dicas    2 dicas extras do modo Locais (4º e 6º chute). Sem citar o nome nem o viajante.
  //   diario   registros reais do diário de bordo (tradução oficial pt-BR), 3 a 6.
  //            Sem esse campo o lugar fica fora do modo Diário.
  //   dlc      só aparece com Echoes of the Eye ligado
  const LOCAIS = [
    // Sol
    { id:"sol", nome:"Sol", alias:["Sun","The Sun","O Sol"],
      tipo:"Estrela", corpo:"Sol", orbita:0, nomai:"Não", perigo:"Calor", viajante:"Nenhum",
      desc:"A estrela do sistema. Está velha, inchada e prestes a fazer algo dramático.",
      dicas:["Os Nomai me estudaram de perto e concluíram que eu ainda tinha muito tempo pela frente.","O que acontece comigo no fim de cada ciclo não foi obra de ninguém. É só a minha idade."] },
    { id:"sun-station", nome:"Estação Solar", alias:["Sun Station"],
      tipo:"Estação", corpo:"Sol", orbita:1, nomai:"Sim", perigo:"Calor", viajante:"Nenhum",
      desc:"Estação Nomai em órbita rasante do Sol, construída pra um experimento que nunca funcionou.",
      dicas:["O experimento planejado aqui nunca chegou a disparar: o alvo se recusou a cooperar.","Uma cientista escreveu, com todas as letras, que eu fui um fracasso."],
      diario:["Há um modo seguro de viajar do Gêmeo Cinzento até a Estação Solar.","Os Nomai discutiram sobre construir uma Estação Solar a fim de energizar o Projeto do Gêmeo Cinzento.","Os Nomai construíram algo chamado de Estação Solar, mas nem todos aprovaram sua construção.","A Estação Solar foi desenvolvida para forçar o sol a ser uma supernova.","Os Nomai dispararam a Estação Solar, mas não afetou o sol. Eles concluíram que a Estação Solar nunca conseguiria levar o sol a ser uma supernova.","Após a Estação Solar falhar, os Nomai deram uma pausa para investigar o cometa recém-chegado."] },

    // Gêmeo Cálido
    { id:"ember-twin", nome:"Gêmeo Cálido", alias:["Gêmea de Brasa","Gêmea de Brasas","Ember","Ember Twin"],
      tipo:"Planeta", corpo:"Gêmeo Cálido", orbita:2, nomai:"Sim", perigo:"Areia", viajante:"Cherte",
      desc:"A gêmea que recebe areia. Cavernas, uma cidade escondida e Cherte no topo.",
      dicas:["Minhas cavernas vão ficando mais apertadas conforme o ciclo avança.","O povo antigo por aqui se escondeu num cânion onde a luz nunca chega."] },
    { id:"chert-camp", nome:"Acampamento de Cherte", alias:["Acampamento de Cherte","Cherte's Camp","Acampamento do Cherte"],
      tipo:"Acampamento", corpo:"Gêmeo Cálido", orbita:2, nomai:"Não", perigo:"Nenhum", viajante:"Cherte",
      desc:"Uma cratera no polo norte do Gêmeo Cálido, com um telescópio, um tambor e um astrônomo cada vez mais nervoso.",
      dicas:["Um tambor marca o ritmo numa cratera no polo norte.","Quem acampa aqui conta as estrelas que se apagam e perde o ânimo a cada visita."],
      diario:["Todas as estrelas do universo estão morrendo, inclusive nosso sol.","As estrelas simplesmente estão morrendo de velhice. Aparentemente elas são mais velhas do que imaginávamos.","Cherte montou seu equipamento de astronomia no polo norte do Gêmeo Cálido.","Cherte observou um estranho aumento no número de supernovas recentemente.","Cherte entrou em estado catatônico ao saber da morte iminente do nosso sol."] },
    { id:"sunless-city", nome:"Cidade do Ocaso", alias:["Sunless City","Cidade sem sol","Cidade Sem Sol"],
      tipo:"Cidade", corpo:"Gêmeo Cálido", orbita:2, nomai:"Sim", perigo:"Areia", viajante:"Nenhum",
      desc:"A cidade Nomai escavada num cânion do Gêmeo Cálido, longe do calor do Sol. A areia acaba tomando tudo.",
      dicas:["Fui erguida em degraus, num cânion fundo, de costas pra luz.","Meus habitantes discutiram por escrito se valia a pena ir atrás de uma lua que some."],
      diario:["Os sobreviventes que caíram no Gêmeo Cálido decidiram buscar abrigo nas cavernas, sob o local da queda da cápsula de escape deles.","Os Nomai descobriram um lugar para abrigarem-se em longo prazo, no fim de umas das passagens sob a cápsula de escape.","Cherte crê que a falta de ruínas na superfície mostra que os Nomai devem ter vivido no subterrâneo.","Há um caminho que leva até o Laboratório de Alta Energia da Cidade do Ocaso.","Eu encontrei um indicador de trilha para a Cidade do Ocaso, mas o caminho está bloqueado.","Uma cidade Nomai construída nas paredes de uma enorme caverna subterrânea. A cidade é dividida verticalmente em quatro distritos."] },
    { id:"high-energy-lab", nome:"Laboratório de Alta Energia", alias:["High Energy Lab","Lab de Alta Energia"],
      tipo:"Laboratório", corpo:"Gêmeo Cálido", orbita:2, nomai:"Sim", perigo:"Nenhum", viajante:"Nenhum",
      desc:"Onde os Nomai provaram que algo pode chegar antes de sair. Pye trabalhou aqui.",
      dicas:["Aqui criaram de propósito duas coisas que não deveriam existir lado a lado.","Foi neste lugar que provaram que uma mensagem pode chegar antes de ser enviada."],
      diario:["Os Nomai conseguiram reproduzir com sucesso a anomalia temporal observada a princípio na Estação do Buraco Branco (objetos transportados parecem chegar antes de partir).","O intervalo de tempo negativo medido na Estação do Buraco Branco foi investigado profundamente no Laboratório de Alta Energia (no canyon no equador Gêmeo Cálido).","O Projeto do Gêmeo Cinzento foi concebido no Laboratório de Alta Energia, um prédio com grandes painéis solares no equador no Gêmeo Cálido.","O Laboratório de Alta Energia só pode ser acessado pela trilha da Cidade do Ocaso.","Os Nomai descobriram que conseguiriam aumentar o intervalo de tempo negativo entre chegada e partida, adicionando energia nos núcleos de transportação.","Os Nomai queriam saber se um intervalo negativo de 22 minutos seria possível. Eles concluíram que era preciso uma nova tecnologia para produzir a energia necessária, assim como um núcleo de translação avançado capaz de suportá-la. O Gêmeo Cinzento foi sugerido como o local para esse projeto."] },
    { id:"lakebed-cave", nome:"Caverna do Fundo Seco do Lago", alias:["Caverna do Fundo do Lago","Lakebed Cave","Cavernas Quânticas","Caverna do Leito do Lago","Caverna do Lago Seco"],
      tipo:"Caverna", corpo:"Gêmeo Cálido", orbita:2, nomai:"Ruínas", perigo:"Areia", viajante:"Nenhum",
      desc:"Um lago que secou há eras. Lá dentro, uma pedra que muda de lugar quando ninguém olha.",
      dicas:["A água foi embora há muito tempo. Ficou uma caverna e uma regra.","Uma pedra aqui dentro só te leva junto se você chegar bem perto e olhar."],
      diario:["Um Nomai chamado Coleus estava em cima da pedra errante quando outra lanterna Nomai se apagou. Quando religaram a lanterna, Coleus e a pedra haviam sumido.","Coleus e Melorae voltaram para analisar a rocha. Na teoria deles, quando um ser consciente entra em contato com um objeto quântico e deixa de observar os arredores, eles podem ficar presos e se moverem juntos.","A rocha errante foi vista pela primeira vez na caverna no fundo seco do lago no polo norte do Gêmeo Cálido.","Um Nomai chamado Coleus desapareceu misteriosamente da caverna no fundo seco do lago no polo norte do Gêmeo Cálido.","Para viajar com um objeto quântico, é necessário ficar sobre o objeto e deixar de observar seus arredores (significando que tem que haver uma completa escuridão). Coleus usou essa regra quântica para escapar da caverna onde ficou preso."] },
    { id:"escape-pod-2", nome:"Cápsula de Escape 2", alias:["Pod de Fuga 2","Escape Pod 2","Pod 2","Cápsula de Fuga 2"],
      tipo:"Ruína", corpo:"Gêmeo Cálido", orbita:2, nomai:"Ruínas", perigo:"Areia", viajante:"Nenhum",
      desc:"O pod que teve o pouso mais violento. Quem estava dentro sobreviveu por pouco.",
      dicas:["Dos três que partiram às pressas, fui o que caiu no lugar mais seco.","Quem saiu de mim precisou cavar pra escapar da areia que subia."],
      diario:["Cherte encontrou destroços Nomai emitindo um sinalizador de luz para o céu, em algum lugar no hemisfério sul do Gêmeo Cálido.","Uma das três cápsulas de escape Nomai pousou em algum lugar nos Gêmeos da Ampulheta.","Uma das três cápsulas de escape Nomai que caíram em nosso sistema solar.","Todas as três cápsulas de escape foram lançadas de algo chamado O Hospedeiro, que estava bem danificado."] },
    { id:"quantum-moon-locator", nome:"Radar da Lua Quântica", alias:["Localizador da Lua Quântica","Quantum Moon Locator","Localizador Quântico"],
      tipo:"Estrutura", corpo:"Gêmeo Cálido", orbita:2, nomai:"Sim", perigo:"Nenhum", viajante:"Nenhum",
      desc:"Um mapa Nomai que mostra em qual planeta a Lua Quântica está agora.",
      dicas:["Sou um mapa de pedra com um ponto que nunca está no mesmo lugar duas vezes.","Os peregrinos me consultavam antes de partir, pra saber onde a lua estava naquele instante."],
      diario:["Um dispositivo Nomai criado para rastrear a localização da Lua Quântica.","Segundo os Nomai, a Lua Quântica deve ser alguma forma de mecânica quântica macroscópica.","A Lua Quântica vaga por cinco locais ao todo."] },

    // Gêmeo Cinzento
    { id:"ash-twin", nome:"Gêmeo Cinzento", alias:["Gêmea de Cinzas","Ash","Ash Twin"],
      tipo:"Planeta", corpo:"Gêmeo Cinzento", orbita:2, nomai:"Sim", perigo:"Areia", viajante:"Nenhum",
      desc:"A gêmea que perde areia. Torres de dobra e um projeto secreto no núcleo.",
      dicas:["Minha superfície escorre pro vizinho ao longo de cada ciclo.","Meu núcleo recebe a energia de uma morte e devolve 22 minutos."] },
    { id:"ash-twin-project", nome:"Projeto do Gêmeo Cinzento", alias:["Ash Twin Project","Projeto Gêmea de Cinzas","ATP","Projeto Ash Twin"],
      tipo:"Laboratório", corpo:"Gêmeo Cinzento", orbita:2, nomai:"Sim", perigo:"Nenhum", viajante:"Nenhum",
      desc:"O maior segredo dos Nomai, escondido no centro do Gêmeo Cinzento. É por causa dele que você lembra de tudo.",
      dicas:["Fui feito pra transformar uma explosão em uma segunda chance.","Máscaras de pedra aqui dentro guardam memórias e as mandam de volta ao passado."],
      diario:["Há oito monólitos com máscaras Nomai presas. Três dessas máscaras estão recebendo dados respectivamente do Módulo de Rastreamento de Sonda, do Profundezas do Gigante e do Recanto Lenhoso.","A câmara central dentro do Gêmeo Cinzento foi selada fisicamente por um imenso e robusto invólucro protetor.","Os Nomai planejaram construir uma tecnologia capaz de produzir um intervalo de tempo negativo de 22 minutos no Gêmeo Cinzento.","Cada memória gravada por uma estátua Nomai é transmitida à unidade de armazenamento correspondente dentro do Gêmeo Cinzento.","Um núcleo de translação avançado foi aprovado para ser instalado na câmara central do Gêmeo Cinzento.","Uma câmara vazia dentro do Gêmeo Cinzento. Os cabos de energia da superfície foram conectados a um invólucro protetor no centro do planeta."] },
    { id:"ash-twin-towers", nome:"Torres do Gêmeo Cinzento", alias:["Ash Twin Towers","Torres de Teletransporte","Torres de Dobra"],
      tipo:"Torre", corpo:"Gêmeo Cinzento", orbita:2, nomai:"Sim", perigo:"Areia", viajante:"Nenhum",
      desc:"Torres alinhadas no equador do Gêmeo Cinzento. Cada uma tem a forma do mundo pra onde leva.",
      dicas:["Cada uma de nós tem a forma do mundo pra onde leva.","Alinhadas no equador, só funcionamos quando o destino está bem acima da cabeça."] },

    // Recanto Lenhoso
    { id:"timber-hearth", nome:"Recanto Lenhoso", alias:["Timber","Timber Hearth"],
      tipo:"Planeta", corpo:"Recanto Lenhoso", orbita:3, nomai:"Ruínas", perigo:"Matéria fantasma", viajante:"Nenhum",
      desc:"Casa. Gêiseres, pinheiros, uma vila na cratera e uma plataforma de lançamento.",
      dicas:["Meus gêiseres são só a parte visível de um interior cheio de túneis.","Um povo antigo tentou me minerar. O povo atual fechou a mina e foi cuidar de foguetes."] },
    { id:"vila", nome:"Vila", alias:["Village","Vila Lenhosa","Aldeia"],
      tipo:"Cidade", corpo:"Recanto Lenhoso", orbita:3, nomai:"Não", perigo:"Nenhum", viajante:"Nenhum",
      desc:"Casas de madeira numa cratera, uma árvore enorme no meio e todo mundo que você conhece.",
      dicas:["Uma árvore enorme me atravessa, e nem todo mundo aqui gosta dela.","Sou o único lugar do sistema onde tem gente brincando de esconde-esconde."],
      diario:["A estátua Nomai no observatório abriu os olhos e me olhou! Vi estranhas luzes brilhantes e as minhas próprias memórias passaram diante de meus olhos.","Hal disse que a estátua nunca abriu os olhos antes (apesar de Corneana ter tentado).","A primeira e única vila Lenhosa, assim como a principal origem das explosões esse planeta."] },
    { id:"museu", nome:"Museu", alias:["Museum","Observatório do Recanto Lenhoso","Observatório"],
      tipo:"Observatório", corpo:"Recanto Lenhoso", orbita:3, nomai:"Não", perigo:"Matéria fantasma", viajante:"Nenhum",
      desc:"O observatório da vila, com uma exposição de tudo que a Outer Wilds Ventures já achou. Hal cuida dele.",
      dicas:["Guardo, numa caixa de vidro com aviso, uma amostra de algo que não se vê.","A peça recém-chegada aqui é a razão de você viver este dia mais de uma vez."] },
    { id:"zero-g-cave", nome:"Caverna de Gravidade Zero", alias:["Zero-G Cave","Caverna Gravidade Zero","Caverna de gravidade"],
      tipo:"Caverna", corpo:"Recanto Lenhoso", orbita:3, nomai:"Não", perigo:"Nenhum", viajante:"Nenhum",
      desc:"Onde os novatos aprendem a flutuar e a consertar coisas antes de sair pro espaço.",
      dicas:["Aqui a gravidade foi desligada de propósito.","Um modelo de nave com peças quebradas serve de treino pra ferramenta de reparo."],
      diario:["Eu consertei brilhantemente outro “satélite” para Gossan.","Soube que Gossan preparou a caverna de gravidade zero caso eu precisasse me atualizar antes do lançamento.","Uma caverna no centro do Recanto Lenhoso e utilizada pelo Outer Wilds Ventures para treinar novos astronautas."] },
    { id:"minas-nomai", nome:"Minas Nomai", alias:["Nomai Mines","Mina","Minas"],
      tipo:"Caverna", corpo:"Recanto Lenhoso", orbita:3, nomai:"Ruínas", perigo:"Matéria fantasma", viajante:"Nenhum",
      desc:"Escavações Nomai que os Lenhosos reaproveitaram e depois fecharam. Tem algo invisível lá dentro.",
      dicas:["Os Nomai começaram a me escavar e não terminaram. Os Lenhosos terminaram e me trancaram.","Deixaram um aviso na minha entrada sobre algo invisível que anda lá dentro."],
      diario:["Os Nomai estavam extraindo minérios em algum lugar no Recanto Lenhoso.","Os Nomai extraíram minérios desse lugar para construir um invólucro protetor, desenvolvido para selar fisicamente a câmara central dentro do Gêmeo Cinzento.","Assim que o invólucro foi finalizado, os Nomai verificaram para garantir que não havia mais nenhuma entrada física ou rachadura.","Os Nomai descobriram uma espécie de forma de vida semiaquática de quatro olhos nos canais próximos à mina."] },
    { id:"radio-tower", nome:"Torre de Rádio", alias:["Radio Tower"],
      tipo:"Torre", corpo:"Recanto Lenhoso", orbita:3, nomai:"Não", perigo:"Nenhum", viajante:"Nenhum",
      desc:"Uma das poucas construções Lenhosas fora da cratera, do outro lado do planeta.",
      dicas:["Fico no alto, ouvindo o que o satélite de espaço profundo manda.","A foto mais estranha que já recebi mostrava uma sombra passando na frente do Sol."] },
    { id:"launch-pad", nome:"Plataforma de Lançamento", alias:["Launch Pad","Plataforma"],
      tipo:"Estrutura", corpo:"Recanto Lenhoso", orbita:3, nomai:"Não", perigo:"Nenhum", viajante:"Nenhum",
      desc:"Uma torre de madeira com um elevador. Sua nave está lá em cima, e Ardósia lá embaixo.",
      dicas:["Um elevador de madeira leva até o meu topo, e um engenheiro fica embaixo resmungando.","Sou o último chão que você pisa antes de sair pro espaço."] },

    // Pedra de Lia
    { id:"attlerock", nome:"Pedra de Lia", alias:["Lua do Recanto Lenhoso","Attlerock","Pedra de Lia"],
      tipo:"Lua", corpo:"Pedra de Lia", orbita:3, nomai:"Ruínas", perigo:"Nenhum", viajante:"Esker",
      desc:"A lua do Recanto Lenhoso. Pequena, cinzenta e com um único morador.",
      dicas:["Sou pequena, cinzenta, e só uma pessoa faz questão de morar em mim.","Do meu polo norte se ouve todo mundo tocando ao mesmo tempo."] },
    { id:"esker-camp", nome:"Acampamento de Esker", alias:["Esker's Camp","Posto Lunar","Lunar Lookout"],
      tipo:"Acampamento", corpo:"Pedra de Lia", orbita:3, nomai:"Não", perigo:"Nenhum", viajante:"Esker",
      desc:"O posto de observação lunar. Tem um telescópio de sinais e alguém assobiando.",
      dicas:["Quem mora aqui reclama que ninguém aparece pra visitar.","Tem mudas de árvore crescendo num lugar sem ar, cuidadas com carinho."],
      diario:["Parece que Esker ainda está na Pedra de Lia. Já está lá há algum tempo.","Esker está cultivando mudas de árvores em seu acampamento. Aparentemente está se dando bem lá, mas pode estar só a tempo demais.","Esker diz que o polo norte da Pedra de Lia (marcado em vermelho no minimapa) é um ótimo lugar para escutar a música dos demais viajantes com um onduloscópio.","Uma plataforma de observação com uma vista espetacular do sistema solar. Esker usa seu onduloscópio aqui para ficar de olho nos outros viajantes."] },

    // Vale Incerto
    { id:"brittle-hollow", nome:"Vale Incerto", alias:["Brittle","Brittle Hollow"],
      tipo:"Planeta", corpo:"Vale Incerto", orbita:4, nomai:"Sim", perigo:"Buraco negro", viajante:"Riebeck",
      desc:"Um planeta desmoronando num buraco negro, com uma cidade pendurada sob a crosta.",
      dicas:["Pedaços de mim caem pra dentro de mim mesmo.","Um povo inteiro preferiu construir pendurado na minha crosta a viver na superfície."] },
    { id:"hanging-city", nome:"Cidade Dependurada", alias:["Hanging City","Cidade Pendurada","Cidade Suspensa"],
      tipo:"Cidade", corpo:"Vale Incerto", orbita:4, nomai:"Sim", perigo:"Buraco negro", viajante:"Nenhum",
      desc:"A cidade Nomai pendurada de cabeça pra baixo sob a crosta do Vale Incerto, dividida em distritos.",
      dicas:["Meus distritos ficam de cabeça pra baixo, ligados por um elevador.","Uma escola, moradias e o caminho pra uma forja, tudo suspenso sobre o abismo."],
      diario:["Os Nomai decidiram migrar para o Antigo Assentamento na geleira norte. Eles usaram cristais de gravidade para criar um caminho estável por baixo da superfície.","Eu encontrei uma alavanca no Distrito do Degelo que eleva e rebaixa a Usina de Buracos Negros.","Os Nomai discutiram sobre como obter o poderoso e altamente avançado núcleo de transportação necessário para o Projeto do Gêmeo Cinzento.","Os Nomai viajaram para esse sistema solar atrás de um sinal mais antigo que o próprio universo. Eles chamaram a fonte desse sinal de o “Olho do universo”.","Há uma grande cidade Nomai ao norte do acampamento de Riebeck.","Uma cidade Nomai suspensa sob a geleira norte do Vale Incerto. A cidade é dividida verticalmente em quatro distritos."] },
    { id:"black-hole-forge", nome:"Usina de Buracos Negros", alias:["Black Hole Forge","Forja","Forja do Buraco Negro"],
      tipo:"Estrutura", corpo:"Vale Incerto", orbita:4, nomai:"Sim", perigo:"Buraco negro", viajante:"Nenhum",
      desc:"Onde os Nomai forjavam núcleos de dobra, pendurada bem em cima do buraco negro.",
      dicas:["Fico pendurada sobre o vazio e só desço quando alguém me chama de longe.","Foi em mim que nasceram os núcleos que viraram o coração das torres."],
      diario:["O ponto de alinhamento de uma torre de translação não é seu receptor de translação. Na verdade, uma torre de translação sempre se alinha com o centro do seu corpo astral correspondente.","O receptor de translação precisa estar localizado no corpo astral relevante (ou em órbita próxima).","A Usina de Buracos Negros é suspensa e fica acima da Cidade Dependurada. Eu encontrei uma alavanca no Distrito do Degelo que eleva e rebaixa a Usina.","O Distrito da Usina de Buracos Negros é o distrito mais alto na Cidade Dependurada.","Uma Nomai chamada Poke tentou criar um núcleo avançado de transportação na Usina de Buracos Negros.","Os Nomai construíram núcleos de translação na Usina de Buracos Negros antes de enviá-los para o Gêmeo Cinzento."] },
    { id:"tower-quantum-knowledge", nome:"Torre do Conhecimento Quântico", alias:["Tower of Quantum Knowledge","Torre Quântica"],
      tipo:"Torre", corpo:"Vale Incerto", orbita:4, nomai:"Sim", perigo:"Buraco negro", viajante:"Nenhum",
      desc:"A torre no polo sul do Vale Incerto que guarda a terceira regra quântica. Uma hora ela cai.",
      dicas:["Guardo a terceira regra, a mais difícil de aceitar.","Meu topo desaba cedo no ciclo. Dá pra entrar em mim pelo outro lado."],
      diario:["Os Nomai construíram um templo na Lua Quântica para ajudá-los na peregrinação até a sexta localização. \"Não se esqueça da regra final: Para explorar a sexta localização, o templo precisa estar no polo norte da lua\".","A peregrinação à Lua Quântica era uma viagem significativa para um Nomai.","Após os dois grupos de Nomai isolados no Gêmeo Cálido e no Vale Incerto se reunirem, encontrar e visitar a Lua Quântica tornou-se o objetivo comum a eles.","Essa torre (localizada no equador do Vale Incerto) guarda conhecimento útil para os Nomai que embarcaram em suas peregrinações à Lua Quântica.","Disseram para uma Nomai chamada Solanum visitou a Torre do Conhecimento Quântico (no equador do Vale Incerto) para aprender sobre a regra final, antes de embarcar em sua peregrinação à Lua Quântica."] },
    { id:"southern-observatory", nome:"Observatório do Sul", alias:["Southern Observatory","Observatório Sul"],
      tipo:"Observatório", corpo:"Vale Incerto", orbita:4, nomai:"Sim", perigo:"Buraco negro", viajante:"Nenhum",
      desc:"De onde os Nomai olharam pra um sinal que não conseguiam ver. Tem um modelo do sistema inteiro.",
      dicas:["Daqui os Nomai tentaram descobrir de onde vinha o sinal que os trouxe pra cá.","Um aparelho aqui dentro aponta pra fora do sistema, pra além do planeta de névoa."],
      diario:["Os Nomai decidiram criar um radar maior e mais elaborado para captar o sinal do Olho no polo sul do Vale Incerto.","De acordo com o conhecimento deles sobre a Lua Quântica, os Nomai acreditavam que o Olho estava em uma órbita distante do sol.","Há duas trilhas abaixo da superfície do Vale Incerto que levam ao observatório. Uma começa no canhão gravitacional e a outra começa na Torre do Conhecimento Quântico.","Riebeck disse que não tem como chegar ao observatório pela superfície (após tentar e falhar), mas provavelmente há uma trilha sob a crosta em algum lugar.","Há uma porta para o observatório na superfície, mas está quebrada.","O radar novo e mais sensível que os Nomai construíram nesse observatório foi incapaz de detectar qualquer traço do sinal do Olho."] },
    { id:"old-settlement", nome:"Antigo Assentamento", alias:["Assentamento Antigo","Old Settlement","Assentamento"],
      tipo:"Ruína", corpo:"Vale Incerto", orbita:4, nomai:"Ruínas", perigo:"Buraco negro", viajante:"Nenhum",
      desc:"O primeiro lugar onde os Nomai se instalaram depois de cair. Uma criança escreveu numa parede aqui.",
      dicas:["Fui a primeira morada dos sobreviventes, antes de decidirem construir pra baixo.","Uma criança deixou desenhos e recados nas minhas paredes."],
      diario:["Os sobreviventes Nomai que caíram no Vale Incerto desceram por um penhasco até um local para se abrigarem abaixo da superfície.","Os Nomai trabalharam juntos para recuperar um sinal com formato de um olho, que eles encontraram quando estavam a bordo do O Hospedeiro.","Os Nomai construíram um assentamento temporário abaixo do local da queda de sua cápsula de escape.","O sinal de certa forma era mais antigo que o próprio universo. Os Nomai decidiram chamá-lo de o \"Olho do Universo\".","Os Nomai abandonaram seu assentamento após uma crescente preocupação em relação a sua estabilidade."] },
    { id:"escape-pod-1", nome:"Cápsula de Escape 1", alias:["Pod de Fuga 1","Escape Pod 1","Pod 1","Cápsula de Fuga 1"],
      tipo:"Ruína", corpo:"Vale Incerto", orbita:4, nomai:"Ruínas", perigo:"Nenhum", viajante:"Nenhum",
      desc:"O pod que teve sorte: caiu num lugar onde o chão aguentou. Annona e Daz vieram nele.",
      dicas:["Fui o primeiro a cair, e o único que caiu num lugar onde dava pra ficar.","Quem saiu de mim andou até um penhasco e desceu."],
      diario:["Uma das três cápsulas de escape Nomai pousou em algum lugar do Vale Incerto.","Uma das três cápsulas de escape Nomai que caíram em nosso sistema solar.","Todas as três cápsulas de escape foram lançadas de algo chamado O Hospedeiro, que estava bem danificado."] },
    { id:"gravity-cannon-bh", nome:"Canhão Gravitacional", alias:["Canhão de Gravidade","Gravity Cannon","Canhão de gravidade do Vale Incerto"],
      tipo:"Estrutura", corpo:"Vale Incerto", orbita:4, nomai:"Sim", perigo:"Nenhum", viajante:"Nenhum",
      desc:"Lança e chama de volta ônibus Nomai. Tem um estacionado que pode te levar até a Lua Quântica.",
      dicas:["Puxo de volta uma nave que foi parar no lugar mais estranho do sistema.","Sem mim, ninguém chegaria ao polo sul da lua que some."],
      diario:["Eu recuperei uma exploradora Nomai da Lua Quântica.","Eu recuperei uma exploradora Nomai no Xereta.","Uma enorme estrutura cilíndrica que gera um forte campo gravitacional ascendente."] },
    { id:"riebeck-camp", nome:"Acampamento de Riebeck", alias:["Riebeck's Camp","Acampamento do Riebeck"],
      tipo:"Acampamento", corpo:"Vale Incerto", orbita:4, nomai:"Não", perigo:"Buraco negro", viajante:"Riebeck",
      desc:"Uma fogueira embaixo da crosta, um banjo e alguém que não quer voar de volta.",
      dicas:["Um banjo toca embaixo da crosta, perto de um cruzamento de caminhos Nomai.","Quem acampa aqui adora o que encontrou, mas tem pavor da viagem de volta."],
      diario:["Riebeck se dirigiu ao Vale Incerto para investigar o que os Nomai faziam no polo sul.","Riebeck aterrissou sua nave próximo à grande cúpula no polo sul. A porta que levava para dentro estava quebrada, então decidiu se dirigir ao norte, até as ruínas no equador, em busca de um caminho por baixo da superfície.","Riebeck descobriu um antigo caminho Nomai próximo ao acampamento no equador. O caminho começa dentro de um prédio em ruínas com árvores crescendo por lá.","Riebeck chegou até as Encruzilhadas e continuou a descer em busca de oxigênio.","Riebeck montou um acampamento no fundo das Encruzilhadas. Sua empolgação por estar em meio a tanta história Nomai só se compara ao medo que sente por buracos negros.","De todo o Recanto Lenhoso, só Riebeck se dedicou à arqueologia. Após superar seu medo do espaço e partir para o Vale Incerto a fim de explorar o imenso tesouro que é a cultura Nomai."] },

    // Luzeiro do Vale
    { id:"hollows-lantern", nome:"Luzeiro do Vale", alias:["Hollows Lantern","Lanterna","Hollow's Lantern","Lanterna do Vale"],
      tipo:"Lua", corpo:"Luzeiro do Vale", orbita:4, nomai:"Não", perigo:"Lava", viajante:"Nenhum",
      desc:"Lua vulcânica que bombardeia o Vale Incerto enquanto encolhe.",
      dicas:["Encolho ao longo do ciclo, e o que perco cai no vizinho.","Sou a razão de o chão de outro mundo viver desabando."] },

    // Profundezas do Gigante
    { id:"giants-deep", nome:"Profundezas do Gigante", alias:["Giants Deep","Giant","Giant's Deep"],
      tipo:"Planeta", corpo:"Profundezas do Gigante", orbita:5, nomai:"Sim", perigo:"Ciclones", viajante:"Gabro",
      desc:"Oceano sem fim, ilhas que voam e ciclones. Gabro aprova.",
      dicas:["Minhas ilhas não ficam paradas, e às vezes saem do planeta.","Uma corrente no fundo empurra tudo pra fora. Só quem se disfarça passa."] },
    { id:"gabbro-island", nome:"Ilha de Gabro", alias:["Ilha de Gabro","Gabro's Island","Ilha do Gabro"],
      tipo:"Ilha", corpo:"Profundezas do Gigante", orbita:5, nomai:"Não", perigo:"Ciclones", viajante:"Gabro",
      desc:"Uma ilha com uma rede e uma flauta. De vez em quando vai parar no espaço.",
      dicas:["Quem descansa aqui numa rede também lembra do ciclo anterior.","Levo meus visitantes pro espaço quando um ciclone passa."],
      diario:["Hal disse que Gabro voltou ao Profundezas do Gigante para tentar aprender mais sobre a estátua Nomai do observatório.","Gabro está descansando numa rede na praia da ilha.","Gabro encontrou a estátua Nomai em outra ilha. Os olhos da estátua começaram a brilhar e Gabro viu suas memórias sendo reproduzidas diante de seus olhos.","Gabro se lembra de ter morrido. Viu suas memórias sendo reproduzidas diante de seus olhos, assim como ocorreu naquela vez com a estátua.","Parece que só eu e Gabro estamos conscientes de que estamos em um loop temporal."] },
    { id:"statue-island", nome:"Ilha da Estátua", alias:["Statue Island","Oficina de Estátuas","Statue Workshop"],
      tipo:"Ilha", corpo:"Profundezas do Gigante", orbita:5, nomai:"Sim", perigo:"Ciclones", viajante:"Nenhum",
      desc:"A oficina onde os Nomai faziam máscaras de pedra que gravam memórias. Uma delas está no museu.",
      dicas:["Aqui foi montado o par de olhos que te encara no começo de tudo.","Uma estátua enorme, quebrada, descansa na minha costa."],
      diario:["Uma das ilhas no Profundezas do Gigante tem uma estátua Nomai na praia, assim como a que Gabro trouxe para o Recanto Lenhoso.","A Ilha da Estátua (como Gabro a chama) é aquela com duas ilhas conectadas por um arco de pedra.","A ilha deve ser onde os Nomai criavam estátuas como aquela do nosso observatório.","Encontrei uma estátua Nomai na praia. Se parece como a que temos no observatório.","Encontrei uma placa de “Oficina de Estátuas” próxima a uma porta quebrada que levava para dentro da ilha.","Algumas crianças Nomai discutiram sobre contornar a porta da Oficina De Estátuas e dar uma olhadinha lá dentro por meio de uma rota alternativa (e mais perigosa)."] },
    { id:"construction-yard", nome:"Estaleiro de Construção", alias:["Ilha do Estaleiro","Construction Yard","Estaleiro"],
      tipo:"Ilha", corpo:"Profundezas do Gigante", orbita:5, nomai:"Sim", perigo:"Ciclones", viajante:"Nenhum",
      desc:"A ilha onde o Canhão de Sonda foi construído. Cassava e Mallow discutiram muito aqui.",
      dicas:["O que foi montado aqui hoje orbita o planeta, com um pedaço a menos.","Dois cientistas discutiram por escrito sobre a potência de um único disparo."],
      diario:["Aqui é a ilha onde os Nomai construíram o Canhão de Sonda Orbital.","Por algum motivo, os Nomai colocaram o Canhão de Sonda Orbital num intervalo por tempo indeterminado. Não mandaram o canhão disparar.","De acordo com um computador Nomai, uma sonda de longo alcance foi recentemente lançada do Canhão de Sonda Orbital.","Os Nomai construíram o Canhão de Sonda Orbital no Estaleiro de Construção, no Profundezas do Gigante."] },
    { id:"bramble-island", nome:"Ilha do Abrolho", alias:["Ilha do Espinheiro","Bramble Island","Ilha Bramble"],
      tipo:"Ilha", corpo:"Profundezas do Gigante", orbita:5, nomai:"Não", perigo:"Peixe-pescador", viajante:"Nenhum",
      desc:"Uma ilha com uma semente do Abrolho Sombrio que cresceu demais. Por dentro, é outro mundo.",
      dicas:["Uma semente de outro mundo cresceu demais em mim.","Por dentro sou maior do que por fora, e cheio de névoa."] },
    { id:"quantum-island", nome:"Torre dos Julgamentos Quânticos", alias:["Tower of Quantum Trials","Ilha Quântica","Quantum Island","Torre das Provações Quânticas"],
      tipo:"Torre", corpo:"Profundezas do Gigante", orbita:5, nomai:"Sim", perigo:"Ciclones", viajante:"Nenhum",
      desc:"Uma torre numa ilha que às vezes não está lá. Ensina o básico sobre coisas que somem.",
      dicas:["Minha ilha vai e volta, como a lua que estudo.","Aqui os Nomai treinavam a segunda regra antes da peregrinação."],
      diario:["Os Nomai detectaram um sinal quântico vindo de algum lugar no Profundezas do Gigante.","Essa torre guarda o conhecimento que um Nomai precisava para fazer sua primeira jornada quântica.","“Analisar um objeto quântico; analisar a imagem de um objeto quântico. Resulta no mesmo.”","Os Nomai a chamaram de “Lei do Pensamento Quântico”.","“Lembre-se, os demais fragmentos quânticos também têm lições a ensinar”."] },
    { id:"probe-tracking-module", nome:"Módulo de Rastreamento de Sonda", alias:["Módulo de Rastreamento da Sonda","Probe Tracking Module","Módulo de Rastreamento"],
      tipo:"Estrutura", corpo:"Profundezas do Gigante", orbita:5, nomai:"Sim", perigo:"Correnteza", viajante:"Nenhum",
      desc:"Caiu do canhão e afundou até o núcleo. Guarda o registro de milhões de disparos.",
      dicas:["Registro milhões de disparos, e só o último importava.","Fico no fundo do oceano, onde a corrente não deixa ninguém passar sem escolta."],
      diario:["Um dos três módulos do Canhão de Sonda Orbital.","O Módulo de Rastreamento de Sonda está recebendo dados da sonda lançada.","Qualquer Nomai a bordo do Módulo de Rastreamento de Sonda seria o primeiro a ver as coordenadas do Olho do universo.","Um computador Nomai informou que o Módulo de Rastreamento de Sonda consta como “desaparecido”.","Eu vi o Módulo de Rastreamento de Sonda através de uma piscina de projeção Nomai. Parece que o Módulo está submerso. Pude ver eletricidade roxa por fora da janela de visualização.","O Canhão de Sonda Orbital lançou milhões de sondas."] },
    { id:"ocean-core", nome:"Profundezas do Oceano", alias:["Núcleo das Profundezas do Gigante","Ocean Core","Núcleo do Oceano","Núcleo"],
      tipo:"Núcleo", corpo:"Profundezas do Gigante", orbita:5, nomai:"Não", perigo:"Correnteza", viajante:"Nenhum",
      desc:"O centro oco do oceano, protegido por uma corrente que empurra tudo pra fora. Águas-vivas ajudam a passar.",
      dicas:["Minhas guardiãs desligam qualquer coisa elétrica que chega perto.","Só se passa pela correnteza vestindo uma delas."],
      diario:["Os Nomai no Estaleiro de Construção viram algo afundar por baixo da correnteza subaquática, o que eles antes achavam impossível.","Passei por uma barreira elétrica e alcancei a floresta de corais no núcleo do planeta.","Gabro disse que há uma forte correnteza por baixo da superfície do oceano que evita que qualquer coisa afunde ali.","Feldspato encontrou um jeito de alcançar o núcleo do Profundezas do Gigante.","O oceano é surpreendente calmo por baixo da correnteza. Algum tipo de campo elétrico reveste o núcleo do planeta."] },
    { id:"probe-cannon", nome:"Canhão de Sonda Orbital", alias:["Canhão de Sonda","Probe Cannon","Cannon","Orbital Probe Cannon"],
      tipo:"Estação", corpo:"Profundezas do Gigante", orbita:5, nomai:"Sim", perigo:"Vácuo", viajante:"Nenhum",
      desc:"Canhão Nomai em órbita das Profundezas do Gigante. Dispara uma vez por ciclo e se parte no processo.",
      dicas:["Disparo uma vez por ciclo, e sempre pro mesmo lugar.","Um pedaço meu caiu no oceano. O resto ficou em órbita."],
      diario:["Utilizei uma piscina de projeção Nomai e vi o interior de uma estação espacial orbitando o Profundezas do Gigante.","Gabro vê uma luz brilhante no céu no início de cada loop. Algo deve estar acontecendo na órbita do Profundezas do Gigante.","Os restos quebrados de uma estação espacial Nomai orbitando o Profundezas do Gigante. Há três caminhos de acesso partindo da área de comando central.","Os Nomai finalizaram a construção do módulo final do Canhão de Sonda Orbital e o colocaram em órbita em torno do Profundezas do Gigante.","Os Nomai decidiram construir um canhão de sonda para orbitar o Profundezas do Gigante.","O Canhão de Sonda Orbital foi criado para encontrar a localização exata do Olho do Universo."] },

    // Abrolho Sombrio
    { id:"dark-bramble", nome:"Abrolho Sombrio", alias:["Bramble","Dark Bramble","Espinheiro Sombrio"],
      tipo:"Planeta", corpo:"Abrolho Sombrio", orbita:6, nomai:"Ruínas", perigo:"Peixe-pescador", viajante:"Feldspato",
      desc:"Névoa, raízes e peixes-pescadores. Maior por dentro do que por fora.",
      dicas:["Sons viajam longe demais dentro de mim, e nem sempre vêm de onde parece.","Quem quer passar pelos meus moradores desliga os motores e não faz barulho."] },
    { id:"feldspar-camp", nome:"Acampamento de Feldspato", alias:["Acampamento de Feldspato","Feldspato's Camp","Acampamento do Feldspato"],
      tipo:"Acampamento", corpo:"Abrolho Sombrio", orbita:6, nomai:"Não", perigo:"Peixe-pescador", viajante:"Feldspato",
      desc:"Uma fogueira dentro de um lugar sem tamanho, com uma gaita tocando baixinho.",
      dicas:["Uma gaita toca dentro de algo que engoliu uma nave.","Só se chega aqui seguindo o som certo pela névoa."],
      diario:["Quando lanço meu batedor dentro da semente que caiu no Recanto Lenhoso, ele acaba indo parar em um espaço bem maior, repleto de névoa e vinhas espinhentas.","Feldspato se dirigiu ao Abrolho Sombrio após chegar até o núcleo do Profundezas do Gigante.","Feldspato não morreu! Sua nave caiu e agora está acampando dentro de um enorme esqueleto de tamboril.","Feldspato não acha que o radar do meu batedor está errado quando mostra que meu batedor está em dois lugares ao mesmo tempo. Sua teoria é de que o espaço não funciona do mesmo jeito dentro do Abrolho Sombrio.","Feldspato não demonstra nenhum desejo de retornar à civilização. Tem aproveitado muito a paz e a quietude (relativas) de lá."] },
    { id:"escape-pod-3", nome:"Cápsula de Escape 3", alias:["Pod de Fuga 3","Escape Pod 3","Pod 3","Cápsula de Fuga 3"],
      tipo:"Ruína", corpo:"Abrolho Sombrio", orbita:6, nomai:"Ruínas", perigo:"Peixe-pescador", viajante:"Nenhum",
      desc:"O pod que não teve sorte. Caiu num lugar de onde ninguém sai, e quem saiu deixou uma trilha de luz.",
      dicas:["Fui o único dos três a cair num lugar sem saída.","Quem saiu de mim andou no escuro deixando luzes pelo caminho."],
      diario:["Uma das três cápsulas de escape Nomai nunca conseguiu sair do Abrolho Sombrio.","Uma das três cápsulas de escape Nomai que caíram em nosso sistema solar.","Todas as três cápsulas de escape foram lançadas de algo chamado O Hospedeiro, que estava bem danificado.","Os sobreviventes da cápsula de escape 3 encontraram dois sinalizadores diferentes vindo do O Hospedeiro, como se estivesse em dois lugares ao mesmo tempo.","Sobreviventes da Cápsula de Escape 3"] },
    { id:"nomai-grave", nome:"Túmulo Nomai", alias:["Nomai Grave","Sepultura Nomai"],
      tipo:"Ruína", corpo:"Abrolho Sombrio", orbita:6, nomai:"Ruínas", perigo:"Peixe-pescador", viajante:"Nenhum",
      desc:"O fim da trilha de luzes que sai do Pod 3. Um lugar silencioso, cheio de ossos e um registro importante.",
      dicas:["Um silêncio cheio de ossos, no fim de uma trilha de luzes.","A semente que fica aqui mostra uma nave enorme lá dentro, se você olhar com o batedor."],
      diario:["Os sobreviventes da cápsula de escape 3 abandonaram os destroços e tentaram retornar ao O Hospedeiro.","Os sobreviventes decidiram seguir o sinalizador mais próximo do O Hospedeiro, devido ao suprimento limitado de ar. Eles planejaram deixar um rastro de luzes pelo caminho caso alguém respondesse ao sinal de socorro.","Os sobreviventes da Cápsula de Escape 3 seguiram um dos dois sinalizadores emitidos pelo O Hospedeiro até uma pequena semente do Abrolho Sombrio, por onde não conseguiram mais avançar.","O sinalizador do O Hospedeiro estava se esvaindo e logo não existiria mais.","Os Nomai mal conseguiram captar o sinalizador do O Hospedeiro dentro da semente, mas a abertura era muito pequena para um único Nomai passar, muito menos uma cápsula de escape.","Se eu lançar meu batedor na semente, poderei tirar fotos de uma enorme nave Nomai abandonada."] },
    { id:"vessel", nome:"O Hospedeiro", alias:["Hospedeiro","Vessel","Nave Nomai","A Nave","The Vessel"],
      tipo:"Nave", corpo:"Abrolho Sombrio", orbita:6, nomai:"Sim", perigo:"Peixe-pescador", viajante:"Nenhum",
      desc:"A nave Nomai que trouxe todos pra cá, presa nas raízes do Abrolho Sombrio.",
      dicas:["Trouxe um povo inteiro atrás de um sinal mais velho que o universo.","Meu núcleo de dobra queimou na queda. Com um novo, ainda dá pra ir embora."],
      diario:["Eu lancei meu batedor na semente no Túmulo Nomai e tirei fotos de uma enorme nave Nomai abandonada.","Os Nomai se transportaram para esse sistema solar em uma espaçonave chamada o Hospedeiro. Eles tentaram seguir o sinal vindo do Olho do Universo.","O Hospedeiro caiu em algum lugar no Abrolho sombrio.","O núcleo de transportação do O Hospedeiro se quebrou com a queda da nave no Abrolho Sombrio.","Encontrei o Hospedeiro Nomai abandonado bem dentro do Abrolho Sombrio.","O núcleo de transportação do O Hospedeiro já morreu há muito tempo."] },

    // Xereta
    { id:"interloper", nome:"Xereta", alias:["Cometa","O Intruso","The Interloper","Interloper"],
      tipo:"Cometa", corpo:"Xereta", orbita:7, nomai:"Ruínas", perigo:"Matéria fantasma", viajante:"Nenhum",
      desc:"Cometa gelado com um passageiro mortal escondido no núcleo.",
      dicas:["Só de passagem, com uma órbita alongada que quase encosta no Sol.","O que carreguei por dentro explica por que um povo inteiro sumiu no mesmo instante."] },
    { id:"interloper-core", nome:"Núcleo Rompido", alias:["Núcleo do Xereta","Interloper Core","Núcleo do Cometa","Fissura do Xereta"],
      tipo:"Núcleo", corpo:"Xereta", orbita:7, nomai:"Ruínas", perigo:"Matéria fantasma", viajante:"Nenhum",
      desc:"O interior do cometa, só acessível quando o gelo derrete perto do Sol. Dois Nomai congelados esperam lá.",
      dicas:["Só se chega aqui quando o gelo derrete, do lado ensolarado.","Dois cientistas desceram até mim. Um tentou voltar pra avisar e não deu tempo."],
      diario:["O equipamento da exploradora captou estranhas leituras vindas de algum lugar sob a superfície.","Duas das Nomai localizaram a fissura no gelo no lado ensolarado do Xereta. Elas desceram até lá dentro para investigar.","Encontrei as duas integrantes da tripulação, da exploradora Nomai, próximo de uma rocha quebrada, que parece ter se implodido.","As Nomai rastrearam as estranhas leituras de energia até uma pedra esférica que cobria alguma forma de matéria exótica.","Elas determinaram que a matéria exótica fosse letal e estava sob extrema pressão. Se a pedra se rompesse, a matéria ali contida iria se expandir rapidamente, apagando quase que completamente o sistema solar.","Uma das Nomai ficou para trás para analisar a matéria alienígena enquanto a outra retornou à superfície para alertar os demais Nomai."] },
    { id:"nomai-shuttle", nome:"Exploradora Nomai Congelada", alias:["Ônibus Nomai do Xereta","Nomai Shuttle","Ônibus Nomai","Shuttle"],
      tipo:"Nave", corpo:"Xereta", orbita:7, nomai:"Sim", perigo:"Nenhum", viajante:"Nenhum",
      desc:"O veículo que Poke e Clary usaram pra chegar ao cometa. Continua estacionado lá.",
      dicas:["Fui deixada estacionada num visitante gelado, com alguém a bordo mantendo o calor.","Um canhão de gravidade me chama de volta de um cometa."],
      diario:["Encontrei uma exploradora Nomai quase que completamente congelada.","Os Nomai pousaram no Xereta logo após a sua chegada ao nosso sistema solar. O equipamento da exploradora captou estranhas leituras vindas de algum lugar sob a superfície.","Havia três Nomai a bordo da exploradora. Uma delas ficou para trás para manter a exploradora aquecida enquanto as outras duas exploraram o Xereta.","Clary, a Nomai que ficou para trás, perdeu contato com as outras duas assim que desceram abaixo da superfície do Xereta."] },

    // Estação do Buraco Branco
    { id:"white-hole-station", nome:"Estação do Buraco Branco", alias:["Estação Buraco Branco","White Hole","White Hole Station"],
      tipo:"Estação", corpo:"Estação do Buraco Branco", orbita:8, nomai:"Sim", perigo:"Nenhum", viajante:"Nenhum",
      desc:"Onde você aparece depois de cair no buraco negro. Tem caminho de volta.",
      dicas:["Fico do lado de fora de tudo, no ponto onde o que cai reaparece.","Os Nomai me usaram de molde pra construir as torres que dobram o espaço."],
      diario:["Muitos Nomai retornaram à estação para investigar a leitura do equipamento que registrava uma violação à causalidade.","Todas as torres de translação Nomai estão sintonizadas a um corpo astral específico.","Para usar uma torre, você precisa estar sobre a plataforma durante o alinhamento da torre com seu corpo astral correspondente (o alinhamento ocorre quando o corpo astral está diretamente acima de você).","Há uma Estação do Buraco Branco do lado oposto ao buraco negro do Vale Incerto.","Os experimentos no Laboratório de Alta Energia foram baseados em achados surpreendentes da Estação do Buraco Branco.","As torres no Gêmeo Cinzento foram feitas no molde da Estação do Buraco Branco."] },

    // Lua Quântica
    { id:"quantum-moon", nome:"Lua Quântica", alias:["Quantum","Quantum Moon"],
      tipo:"Lua", corpo:"Lua Quântica", orbita:null, nomai:"Sim", perigo:"Nenhum", viajante:"Solanum",
      desc:"A lua que só existe onde alguém observa. Solanum espera lá.",
      dicas:["Só apareço em um lugar por vez, e só enquanto alguém olha.","Tenho um sexto destino que não dá pra ver da superfície de nenhum planeta."],
      diario:["Os Nomai no Vale Incerto observaram a lua fantasma que às vezes aparece no céu.","Os Nomai no Gêmeo Cálido observaram a lua que desaparecia quando ninguém a via.","Encontrei uma Nomai morta usando traje espacial no polo sul.","Uma Nomai chamada Solanum aterrissou sua exploradora na Lua Quântica.","As anotações de pesquisa de Cherte mencionam uma Lua Quântica que os Lenhosos nunca conseguiram pousar.","Fui capaz de aterrissar na superfície da Lua Quântica."] },
    { id:"quantum-shrine", nome:"Templo Quântico", alias:["Santuário Quântico","Quantum Shrine","Santuário"],
      tipo:"Estrutura", corpo:"Lua Quântica", orbita:null, nomai:"Sim", perigo:"Nenhum", viajante:"Nenhum",
      desc:"O santuário no polo sul da Lua Quântica. Feche a porta, apague a luz e olhe de novo.",
      dicas:["Feche a porta, apague a luz e olhe de novo: você não estará mais onde estava.","Sou a chave pra chegar ao lugar que a lua visita em segredo."],
      diario:["“Lembre-se da lei da sexta localização” está inscrito próximo a um mural de uma torre suspensa sobre um buraco negro.","Os Nomai construíram um templo na Lua Quântica para ajudá-los na peregrinação até a sexta localização.","Um templo Nomai que vaga em volta da Lua Quântica.","“Você se lembrou da lei do pensamento quântico” está inscrito próximo a um mural de uma torre na ilha.","“Lembre-se da lei da confusão quântica” está inscrito próximo a um mural de um fragmento quântico na caverna."] },

    // DLC (Echoes of the Eye)
    { id:"stranger", nome:"O Desconhecido", alias:["O Estranho","Stranger","Forasteiro","The Stranger","Estranho"], dlc:true,
      tipo:"Nave", corpo:"O Desconhecido", orbita:9, nomai:"Não", perigo:"Escuridão", viajante:"Nenhum",
      desc:"Um anel escondido na luz do Sol, cheio de água, escuridão e segredos. (Echoes of the Eye)",
      dicas:["Por fora sou só uma sombra passando na frente do Sol.","Meus moradores dormem e sonham num lugar sem luz, e apagaram os próprios registros."] }
  ];

  // Colunas da grade. type:"num" compara e mostra seta; near = grupos que dão "parcial".
  const COLS_LOCAIS = [
    { k:"tipo",     l:"Tipo" },
    { k:"corpo",    l:"Corpo",  title:"Corpo celeste onde fica",
      near:[["Recanto Lenhoso","Pedra de Lia"],["Gêmeo Cálido","Gêmeo Cinzento"],["Vale Incerto","Luzeiro do Vale"],["Profundezas do Gigante"],["Sol"]] },
    { k:"orbita",   l:"Órbita", type:"num", title:"Posição do corpo a partir do Sol" },
    { k:"nomai",    l:"Nomai",  near:[["Sim","Ruínas"]] },
    { k:"perigo",   l:"Perigo" },
    { k:"viajante", l:"Viajante" }
  ];

  // PERSONAGENS: local precisa ser o nome de um item de LOCAIS (o build confere).
  //   status é no começo do ciclo. dicas: 2 dicas extras (4º e 6º chute).
  const PERSONAGENS = [
    // Lenhosos
    { id:"slate", nome:"Ardósia", alias:["Ardósia"], especie:"Lenhoso", local:"Recanto Lenhoso", papel:"Engenharia", instrumento:"Nenhum", status:"Vivo",
      desc:"Construiu a sua nave (e quase todas as outras) e garante que o para-brisa aguenta.",
      dicas:["Construiu a nave que você pilota e não tem vergonha de nenhum defeito dela.","Fica sentado perto de uma fogueira, embaixo do elevador, dizendo que qualquer problema é problema seu."] },
    { id:"hornfels", nome:"Corneana", alias:["Corneana"], especie:"Lenhoso", local:"Recanto Lenhoso", papel:"Liderança", instrumento:"Nenhum", status:"Vivo",
      desc:"Comanda a Outer Wilds Ventures do alto do observatório.",
      dicas:["Cuida do programa espacial inteiro e da exposição do museu.","Tentou de tudo pra fazer a estátua abrir os olhos, sem sucesso."] },
    { id:"gossan", nome:"Gossan", especie:"Lenhoso", local:"Recanto Lenhoso", papel:"Instrução", instrumento:"Nenhum", status:"Vivo",
      desc:"Te ensinou a pilotar e ainda te lembra de usar o cinto.",
      dicas:["Ensinou você a voar e ainda oferece um último treino antes do lançamento.","Espera na frente de uma caverna onde a gravidade foi desligada."] },
    { id:"hal", nome:"Hal", especie:"Lenhoso", local:"Recanto Lenhoso", papel:"Curadoria", instrumento:"Nenhum", status:"Vivo",
      desc:"Cuida do museu e é seu melhor amigo desde criança.",
      dicas:["Passa o dia ao lado da peça nova do museu e ajudou a trazê-la pra cá.","Foi quem viu a estátua te olhar e disse que nunca tinha acontecido antes."] },
    { id:"gneiss", nome:"Gneiss", especie:"Lenhoso", local:"Recanto Lenhoso", papel:"Música", instrumento:"Banjo", status:"Vivo",
      desc:"Fez os instrumentos de todos os viajantes e toca perto da fogueira.",
      dicas:["Fez com as próprias mãos os instrumentos que os viajantes tocam pelo sistema.","Toca na parte alta da vila, ao lado de uma fogueira, e sente falta de quem partiu."] },
    { id:"chert", nome:"Cherte", alias:["Cherte"], especie:"Lenhoso", local:"Gêmeo Cálido", papel:"Viajante", instrumento:"Tambor", status:"Vivo",
      desc:"Astrônomo do grupo. Acampa no topo do Gêmeo Cálido e percebe que as estrelas estão morrendo.",
      dicas:["Passa o ciclo contando estrelas que se apagam, e fica mais quieto a cada vez.","Deixou anotações sobre uma lua onde ninguém do seu povo conseguiu pousar."] },
    { id:"esker", nome:"Esker", especie:"Lenhoso", local:"Pedra de Lia", papel:"Viajante", instrumento:"Assobio", status:"Vivo",
      desc:"Cuida do posto de observação lunar e reclama que ninguém visita.",
      dicas:["Único morador de um lugar sem ar, cultivando mudas de árvore.","Ouve a música de todos os outros viajantes e reclama que ninguém visita."] },
    { id:"riebeck", nome:"Riebeck", especie:"Lenhoso", local:"Vale Incerto", papel:"Viajante", instrumento:"Banjo", status:"Vivo",
      desc:"Ama arqueologia Nomai. Odeia voar.",
      dicas:["Adora ruínas e escreve sobre elas, mas tem pavor de voar.","Montou acampamento embaixo de uma crosta, perto de um cruzamento Nomai."] },
    { id:"gabbro", nome:"Gabro", alias:["Gabro"], especie:"Lenhoso", local:"Profundezas do Gigante", papel:"Viajante", instrumento:"Flauta", status:"Vivo",
      desc:"Deitado numa rede, olhando as ondas. Também lembra dos loops, mas não se estressa.",
      dicas:["É a única outra pessoa que sabe que o ciclo se repete, e não parece se importar.","Descansa numa rede tocando flauta e também viu a estátua abrir os olhos."] },
    { id:"feldspar", nome:"Feldspato", alias:["Feldspato"], especie:"Lenhoso", local:"Abrolho Sombrio", papel:"Viajante", instrumento:"Gaita", status:"Vivo",
      desc:"Primeira pessoa a voar. Sumiu há anos, mas segue firme lá dentro.",
      dicas:["Todo mundo na vila acha que morreu. A gaita diz o contrário.","Foi a primeira pessoa a voar e acabou dentro de algo que engoliu a própria nave."] },
    { id:"tephra", nome:"Tefra", alias:["Tefra"], especie:"Lenhoso", local:"Recanto Lenhoso", papel:"Criança", instrumento:"Nenhum", status:"Vivo",
      desc:"Comanda a brincadeira de esconde-esconde na vila.",
      dicas:["Comanda o esconde-esconde e te desafia a achar os amigos.","Fica perto da entrada da vila, com tudo a ver com o telescópio de sinais."] },
    { id:"galena", nome:"Galena", especie:"Lenhoso", local:"Recanto Lenhoso", papel:"Criança", instrumento:"Nenhum", status:"Vivo",
      desc:"Está escondida em algum lugar da vila. Boa sorte.",
      dicas:["Se esconde tão bem que só dá pra achar pelo som.","Faz parte de um esconde-esconde que nunca acaba."] },
    { id:"mica", nome:"Mica", especie:"Lenhoso", local:"Recanto Lenhoso", papel:"Criança", instrumento:"Nenhum", status:"Vivo",
      desc:"Te empresta uma nave de brinquedo pra treinar pouso.",
      dicas:["Tem um brinquedo que voa de verdade, feito pelo mesmo engenheiro da sua nave.","Fica perto da plataforma de lançamento, orgulhoso do modelo."] },
    { id:"moraine", nome:"Moraina", alias:["Moraina"], especie:"Lenhoso", local:"Recanto Lenhoso", papel:"Criança", instrumento:"Nenhum", status:"Vivo",
      desc:"Fica no alto com o telescópio de sinais, ouvindo a música dos viajantes.",
      dicas:["Sonha em ser viajante e treina ouvindo os outros de longe.","Fica num ponto alto da vila com um telescópio de sinais apontado pro céu."] },
    { id:"arkose", nome:"Arcose", alias:["Arcose"], especie:"Lenhoso", local:"Recanto Lenhoso", papel:"Criança", instrumento:"Nenhum", status:"Vivo",
      desc:"Mais uma criança escondida pela vila.",
      dicas:["Prefere se esconder no alto, onde ninguém procura.","Só sai do esconderijo quando você acha."] },
    { id:"marl", nome:"Marga", alias:["Marga"], especie:"Lenhoso", local:"Recanto Lenhoso", papel:"Ofício", instrumento:"Nenhum", status:"Vivo",
      desc:"Quer derrubar a árvore gigante no meio da vila. Ninguém deixa.",
      dicas:["Anda com um machado e um plano que ninguém aprovou.","Tem certeza de que a árvore no meio da vila precisa cair."] },
    { id:"spinel", nome:"Espinela", alias:["Espinela"], especie:"Lenhoso", local:"Recanto Lenhoso", papel:"Ofício", instrumento:"Nenhum", status:"Vivo",
      desc:"Pesca ao lado da vila e não pega muita coisa.",
      dicas:["Fica com uma vara na mão, esperando algo que nunca aparece.","Tem mais paciência que peixe."] },
    { id:"porphy", nome:"Pórfiro", alias:["Pórfiro"], especie:"Lenhoso", local:"Recanto Lenhoso", papel:"Ofício", instrumento:"Nenhum", status:"Vivo",
      desc:"Faz uma bebida com seiva da árvore e insiste pra você provar.",
      dicas:["Produz uma bebida com seiva de pinheiro e guarda em barris.","Fica perto dos barris, satisfeito com a safra."] },
    { id:"tektite", nome:"Tektite", especie:"Lenhoso", local:"Recanto Lenhoso", papel:"Ofício", instrumento:"Nenhum", status:"Vivo",
      desc:"Trabalha na mina e sabe onde tem matéria fantasma.",
      dicas:["Vigia a entrada de uma mina fechada há muito tempo.","Avisa sobre algo invisível lá dentro que mata quem encosta."] },

    // Nomai
    { id:"solanum", nome:"Solanum", especie:"Nomai", local:"Lua Quântica", papel:"Peregrina", instrumento:"Nenhum", status:"Vivo",
      desc:"A última Nomai que você pode encontrar. Se olhar no lugar certo.",
      dicas:["Chegou a um lugar de onde ninguém volta, e continua lá esperando.","Conversa escrevendo no chão e responde às perguntas que você monta com pedras."] },
    { id:"poke", nome:"Poke", especie:"Nomai", local:"Gêmeo Cinzento", papel:"Cientista", instrumento:"Nenhum", status:"Morto",
      desc:"Projetou os núcleos de dobra e o Projeto do Gêmeo Cinzento.",
      dicas:["Projetou os núcleos de dobra e assinou o plano mais ambicioso do seu povo.","Desceu ao interior de um cometa e tentou voltar pra avisar. Não deu tempo."] },
    { id:"pye", nome:"Pye", especie:"Nomai", local:"Estação Solar", papel:"Cientista", instrumento:"Nenhum", status:"Morto",
      desc:"Direta ao ponto: se o Sol não coopera, a gente ajuda ele a explodir.",
      dicas:["Escreveu com raiva que a estação perto do Sol era um fracasso, e estava certa.","Desceu ao interior de um cometa e ficou pra analisar o que encontrou."] },
    { id:"clary", nome:"Clary", especie:"Nomai", local:"Estação Solar", papel:"Cientista", instrumento:"Nenhum", status:"Morto",
      desc:"Trabalhou na Estação Solar e foi investigar o cometa com Poke.",
      dicas:["Ajudou a construir a estação mais perto do Sol.","Ficou na exploradora mantendo o calor e nunca viu as colegas voltarem."] },
    { id:"cassava", nome:"Cassava", especie:"Nomai", local:"Profundezas do Gigante", papel:"Cientista", instrumento:"Nenhum", status:"Morto",
      desc:"Trabalhou no Canhão de Sonda e tinha certeza de que Mallow ia explodir tudo.",
      dicas:["Tinha certeza de que um disparo na potência máxima ia quebrar tudo.","Trabalhou onde o canhão foi montado, e perdeu a discussão."] },
    { id:"mallow", nome:"Mallow", especie:"Nomai", local:"Profundezas do Gigante", papel:"Cientista", instrumento:"Nenhum", status:"Morto",
      desc:"Queria disparar o canhão na potência máxima. Conseguiu.",
      dicas:["Queria o disparo na potência máxima e conseguiu.","O canhão perdeu um pedaço, e a sonda encontrou o que precisava."] },
    { id:"daz", nome:"Daz", especie:"Nomai", local:"Vale Incerto", papel:"Criança", instrumento:"Nenhum", status:"Morto",
      desc:"Chegou no pod de fuga ainda criança e cresceu vendo a cidade ser construída.",
      dicas:["Chegou ainda criança e desenhou nas paredes do primeiro assentamento.","Cresceu vendo uma cidade ser construída de cabeça pra baixo."] },
    { id:"coleus", nome:"Coleus", especie:"Nomai", local:"Gêmeo Cálido", papel:"Criança", instrumento:"Nenhum", status:"Morto",
      desc:"Sumiu de vista ao apagar a luz numa caverna quântica. E descobriu uma regra.",
      dicas:["Sumiu de vista numa caverna quando a luz apagou, e reapareceu em outro lugar.","Ajudou a descobrir que dá pra viajar junto com uma pedra que muda de lugar."] },
    { id:"melorae", nome:"Melorae", especie:"Nomai", local:"Gêmeo Cálido", papel:"Cientista", instrumento:"Nenhum", status:"Morto",
      desc:"Estudou as cavernas quânticas ao lado de Coleus.",
      dicas:["Estudou pedras que mudam de lugar ao lado de um aprendiz curioso.","Registrou na parede da caverna o sumiço e a volta do aprendiz."] },
    { id:"escall", nome:"Escall", especie:"Nomai", local:"O Hospedeiro", papel:"Liderança", instrumento:"Nenhum", status:"Morto",
      desc:"Comandava a nave que respondeu ao sinal do Olho. Nunca saiu do Abrolho Sombrio.",
      dicas:["Decidiu seguir um sinal mais antigo que o universo, e o clã inteiro foi junto.","Ficou na nave depois que as cápsulas partiram. O núcleo de dobra queimou na queda."] },
    { id:"filix", nome:"Filix", especie:"Nomai", local:"Gêmeo Cálido", papel:"Exploração", instrumento:"Nenhum", status:"Morto",
      desc:"Sobreviveu ao pouso do Pod 2 e abriu caminho pelas cavernas.",
      dicas:["Sobreviveu à queda no planeta de areia e abriu caminho pelas cavernas.","Levou os sobreviventes até um cânion onde o Sol não chega."] },
    { id:"annona", nome:"Annona", especie:"Nomai", local:"Vale Incerto", papel:"Liderança", instrumento:"Nenhum", status:"Morto",
      desc:"Veio no Pod 1 e organizou os sobreviventes no assentamento antigo.",
      dicas:["Guiou os sobreviventes da primeira cápsula até um lugar seguro.","Deixou registros preocupados sobre quem estava na terceira cápsula."] },
    { id:"bells", nome:"Bells", especie:"Nomai", local:"Abrolho Sombrio", papel:"Exploração", instrumento:"Nenhum", status:"Morto",
      desc:"Saiu do Pod 3 a pé, no escuro, deixando uma trilha de luzes pra quem viesse depois.",
      dicas:["Saiu a pé, no escuro, deixando luzes pra quem viesse depois.","Foi até onde encontraram a nave, e ficou lá."] },

    // DLC
    { id:"prisioneiro", nome:"Prisioneiro", alias:["Prisoner","The Prisoner","O Prisioneiro"], especie:"Outro", local:"O Desconhecido", papel:"Prisioneiro", instrumento:"Nenhum", status:"Vivo", dlc:true,
      desc:"Trancado há eras por ter feito o que achou certo. (Echoes of the Eye)",
      dicas:["Trancado há eras por ter feito o que achou certo.","Conta a própria história sem palavras, com uma lanterna e uma visão."] }
  ];

  const COLS_PERSONAGENS = [
    { k:"especie",     l:"Espécie" },
    { k:"local",       l:"Local" },
    { k:"papel",       l:"Papel" },
    { k:"instrumento", l:"Instrumento" },
    { k:"status",      l:"Status" }
  ];

  return { LOCAIS, COLS_LOCAIS, PERSONAGENS, COLS_PERSONAGENS };
})();
